
#include "nuitka/prelude.h"
#include "structseq.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *Nuitka_dunder_compiled_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_float_0_0;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_6;
PyObject *const_int_pos_7;
PyObject *const_int_pos_8;
PyObject *const_int_pos_9;
PyObject *const_str_empty;
PyObject *const_dict_empty;
PyObject *const_int_pos_10;
PyObject *const_int_pos_11;
PyObject *const_int_pos_12;
PyObject *const_int_pos_13;
PyObject *const_int_pos_14;
PyObject *const_int_pos_15;
PyObject *const_int_pos_16;
PyObject *const_int_pos_17;
PyObject *const_int_pos_18;
PyObject *const_int_pos_19;
PyObject *const_int_pos_20;
PyObject *const_int_pos_21;
PyObject *const_int_pos_22;
PyObject *const_int_pos_23;
PyObject *const_int_pos_24;
PyObject *const_int_pos_25;
PyObject *const_int_pos_26;
PyObject *const_int_pos_27;
PyObject *const_int_pos_32;
PyObject *const_int_pos_33;
PyObject *const_int_pos_35;
PyObject *const_int_pos_36;
PyObject *const_int_pos_37;
PyObject *const_int_pos_39;
PyObject *const_int_pos_46;
PyObject *const_int_pos_59;
PyObject *const_int_pos_60;
PyObject *const_int_pos_63;
PyObject *const_int_pos_64;
PyObject *const_int_pos_65;
PyObject *const_int_pos_66;
PyObject *const_int_pos_67;
PyObject *const_int_pos_68;
PyObject *const_int_pos_69;
PyObject *const_int_pos_70;
PyObject *const_int_pos_71;
PyObject *const_int_pos_72;
PyObject *const_int_pos_73;
PyObject *const_int_pos_74;
PyObject *const_int_pos_75;
PyObject *const_int_pos_76;
PyObject *const_int_pos_77;
PyObject *const_int_pos_78;
PyObject *const_int_pos_79;
PyObject *const_int_pos_80;
PyObject *const_int_pos_81;
PyObject *const_int_pos_82;
PyObject *const_int_pos_83;
PyObject *const_int_pos_84;
PyObject *const_int_pos_85;
PyObject *const_int_pos_86;
PyObject *const_int_pos_87;
PyObject *const_int_pos_88;
PyObject *const_int_pos_89;
PyObject *const_int_pos_90;
PyObject *const_int_pos_91;
PyObject *const_int_pos_92;
PyObject *const_int_pos_93;
PyObject *const_int_pos_94;
PyObject *const_int_pos_95;
PyObject *const_int_pos_96;
PyObject *const_int_pos_97;
PyObject *const_int_pos_98;
PyObject *const_int_pos_99;
PyObject *const_str_chr_42;
PyObject *const_bytes_empty;
PyObject *const_int_pos_100;
PyObject *const_int_pos_101;
PyObject *const_int_pos_102;
PyObject *const_int_pos_103;
PyObject *const_int_pos_104;
PyObject *const_int_pos_105;
PyObject *const_int_pos_106;
PyObject *const_int_pos_109;
PyObject *const_int_pos_110;
PyObject *const_int_pos_111;
PyObject *const_int_pos_112;
PyObject *const_int_pos_113;
PyObject *const_int_pos_115;
PyObject *const_int_pos_116;
PyObject *const_int_pos_117;
PyObject *const_int_pos_118;
PyObject *const_int_pos_119;
PyObject *const_int_pos_127;
PyObject *const_int_pos_255;
PyObject *const_str_newline;
PyObject *const_str_plain__;
PyObject *const_str_plain_b;
PyObject *const_str_plain_i;
PyObject *const_str_plain_x;
PyObject *const_str_plain_y;
PyObject *const_tuple_empty;
PyObject *const_str_plain_A0;
PyObject *const_str_plain_A2;
PyObject *const_str_plain_A4;
PyObject *const_str_plain_A5;
PyObject *const_str_plain_A6;
PyObject *const_str_plain_D2;
PyObject *const_str_plain_IN;
PyObject *const_str_plain_id;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_H07;
PyObject *const_str_plain_I2C;
PyObject *const_str_plain_J04;
PyObject *const_str_plain_J05;
PyObject *const_str_plain_J06;
PyObject *const_str_plain_LOW;
PyObject *const_str_plain_MSB;
PyObject *const_str_plain_OUT;
PyObject *const_str_plain_P16;
PyObject *const_str_plain_P17;
PyObject *const_str_plain_PC0;
PyObject *const_str_plain_Pin;
PyObject *const_str_plain_SCL;
PyObject *const_str_plain_SDA;
PyObject *const_str_plain_SPI;
PyObject *const_str_plain_bit;
PyObject *const_str_plain_buf;
PyObject *const_str_plain_end;
PyObject *const_str_plain_get;
PyObject *const_str_plain_i2c;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_reg;
PyObject *const_str_plain_sck;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_val;
PyObject *const_int_pos_100000;
PyObject *const_str_plain_AA00;
PyObject *const_str_plain_AA01;
PyObject *const_str_plain_AA02;
PyObject *const_str_plain_BB00;
PyObject *const_str_plain_Chip;
PyObject *const_str_plain_Enum;
PyObject *const_str_plain_GPIO;
PyObject *const_str_plain_HIGH;
PyObject *const_str_plain_MISO;
PyObject *const_str_plain_MOSI;
PyObject *const_str_plain_None;
PyObject *const_str_plain_PA14;
PyObject *const_str_plain_PA15;
PyObject *const_str_plain_PA16;
PyObject *const_str_plain_PWM1;
PyObject *const_str_plain_PWM2;
PyObject *const_str_plain_PWM3;
PyObject *const_str_plain_S805;
PyObject *const_str_plain_S905;
PyObject *const_str_plain_T186;
PyObject *const_str_plain_T194;
PyObject *const_str_plain_T210;
PyObject *const_str_plain__spi;
PyObject *const_str_plain_addr;
PyObject *const_str_plain_attr;
PyObject *const_str_plain_bits;
PyObject *const_str_plain_chip;
PyObject *const_str_plain_data;
PyObject *const_str_plain_file;
PyObject *const_str_plain_init;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_line;
PyObject *const_str_plain_miso;
PyObject *const_str_plain_mode;
PyObject *const_str_plain_mosi;
PyObject *const_str_plain_name;
PyObject *const_str_plain_nano;
PyObject *const_str_plain_open;
PyObject *const_str_plain_path;
PyObject *const_str_plain_pull;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_scan;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_site;
PyObject *const_str_plain_stop;
PyObject *const_str_plain_time;
PyObject *const_str_plain_type;
PyObject *const_float_minus_0_0;
PyObject *const_str_plain_Board;
PyObject *const_str_plain_False;
PyObject *const_str_plain_SAMA5;
PyObject *const_str_plain_SCL_1;
PyObject *const_str_plain_SDA_1;
PyObject *const_str_plain_SMBus;
PyObject *const_str_plain_STM32;
PyObject *const_str_plain_SUN8I;
PyObject *const_str_plain__mode;
PyObject *const_str_plain_blink;
PyObject *const_str_plain_board;
PyObject *const_str_plain_busio;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_clock;
PyObject *const_str_plain_close;
PyObject *const_str_plain_const;
PyObject *const_str_plain_count;
PyObject *const_str_plain_flags;
PyObject *const_str_plain_input;
PyObject *const_str_plain_items;
PyObject *const_str_plain_level;
PyObject *const_str_plain_model;
PyObject *const_str_plain_other;
PyObject *const_str_plain_phase;
PyObject *const_str_plain_pixel;
PyObject *const_str_plain_print;
PyObject *const_str_plain_quill;
PyObject *const_str_plain_range;
PyObject *const_str_plain_setup;
PyObject *const_str_plain_sleep;
PyObject *const_str_plain_start;
PyObject *const_str_plain_tegra;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_types;
PyObject *const_str_plain_utime;
PyObject *const_str_plain_value;
PyObject *const_str_plain_write;
PyObject *const_str_plain_AM33XX;
PyObject *const_str_plain_FT232H;
PyObject *const_str_plain_HFU540;
PyObject *const_str_plain_IMX8MX;
PyObject *const_str_plain_MASTER;
PyObject *const_str_plain_PUD_UP;
PyObject *const_str_plain_SAMD21;
PyObject *const_str_plain___eq__;
PyObject *const_str_plain__value;
PyObject *const_str_plain_append;
PyObject *const_str_plain_atexit;
PyObject *const_str_plain_buffer;
PyObject *const_str_plain_deinit;
PyObject *const_str_plain_format;
PyObject *const_str_plain_in_end;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_object;
PyObject *const_str_plain_origin;
PyObject *const_str_plain_output;
PyObject *const_str_plain_pin_id;
PyObject *const_str_plain_result;
PyObject *const_str_plain_unlock;
PyObject *const_str_plain_xavier;
PyObject *const_tuple_none_tuple;
PyObject *const_tuple_true_tuple;
PyObject *const_str_plain_APQ8016;
PyObject *const_str_plain_BCM2XXX;
PyObject *const_str_plain_DAP1_FS;
PyObject *const_str_plain_ESP8266;
PyObject *const_str_plain_PULL_UP;
PyObject *const_str_plain_SPI0_CS;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain__locked;
PyObject *const_str_plain_address;
PyObject *const_str_plain_ap_chip;
PyObject *const_str_plain_chip_id;
PyObject *const_str_plain_cleanup;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_dirname;
PyObject *const_str_plain_environ;
PyObject *const_str_plain_esp8266;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_out_end;
PyObject *const_str_plain_pwmOuts;
PyObject *const_str_plain_request;
PyObject *const_str_plain_setmode;
PyObject *const_str_plain_writeto;
PyObject *const_tuple_false_tuple;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_angle_listcomp;
PyObject *const_str_plain_AUD_MCLK;
PyObject *const_str_plain_DAP1_DIN;
PyObject *const_str_plain_Detector;
PyObject *const_str_plain_I2C0_SCL;
PyObject *const_str_plain_I2C0_SDA;
PyObject *const_str_plain_I2C1_SCL;
PyObject *const_str_plain_I2C1_SDA;
PyObject *const_str_plain_I2C2_SCL;
PyObject *const_str_plain_I2C2_SDA;
PyObject *const_str_plain_Lockable;
PyObject *const_str_plain_PUD_DOWN;
PyObject *const_str_plain_SPI1_CS0;
PyObject *const_str_plain_SPI1_CS1;
PyObject *const_str_plain_SPI1_SCK;
PyObject *const_str_plain_TWI0_SCL;
PyObject *const_str_plain_TWI0_SDA;
PyObject *const_str_plain_UART1_RX;
PyObject *const_str_plain_UART1_TX;
PyObject *const_str_plain_UART2_RX;
PyObject *const_str_plain_UART2_TX;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___repr__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain_agnostic;
PyObject *const_str_plain_baudrate;
PyObject *const_str_plain_board_id;
PyObject *const_str_plain_detector;
PyObject *const_str_plain_exc_type;
PyObject *const_str_plain_firstbit;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_i2cPorts;
PyObject *const_str_plain_in_start;
PyObject *const_str_plain_platform;
PyObject *const_str_plain_polarity;
PyObject *const_str_plain_property;
PyObject *const_str_plain_readinto;
PyObject *const_str_plain_register;
PyObject *const_str_plain_spiPorts;
PyObject *const_str_plain_try_lock;
PyObject *const_str_angle_metaclass;
PyObject *const_str_plain_DAP1_DOUT;
PyObject *const_str_plain_DAP1_SCLK;
PyObject *const_str_plain_I2C_PORTS;
PyObject *const_str_plain_ODROID_C2;
PyObject *const_str_plain_PULL_DOWN;
PyObject *const_str_plain_PULL_NONE;
PyObject *const_str_plain_SPI0_MISO;
PyObject *const_str_plain_SPI0_MOSI;
PyObject *const_str_plain_SPI0_SCLK;
PyObject *const_str_plain_SPI1_MISO;
PyObject *const_str_plain_SPI1_MOSI;
PyObject *const_str_plain_SPI1_SCLK;
PyObject *const_str_plain_SPI_PORTS;
PyObject *const_str_plain_TEGRA_SOC;
PyObject *const_str_plain_UART1_CTS;
PyObject *const_str_plain_UART1_RTS;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain_buffer_in;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_exc_value;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_out_start;
PyObject *const_str_plain_read_byte;
PyObject *const_str_plain_traceback;
PyObject *const_str_plain_uartPorts;
PyObject *const_str_plain_UART_PORTS;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain_bcm_number;
PyObject *const_str_plain_buffer_out;
PyObject *const_str_plain_read_bytes;
PyObject *const_str_plain_GENERIC_X86;
PyObject *const_str_plain_GIANT_BOARD;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_micropython;
PyObject *const_str_plain_setwarnings;
PyObject *const_str_plain_write_bytes;
PyObject *const_str_plain_write_value;
PyObject *const_tuple_int_pos_1_tuple;
PyObject *const_tuple_int_pos_2_tuple;
PyObject *const_tuple_int_pos_3_tuple;
PyObject *const_tuple_int_pos_4_tuple;
PyObject *const_tuple_int_pos_5_tuple;
PyObject *const_tuple_int_pos_6_tuple;
PyObject *const_tuple_int_pos_7_tuple;
PyObject *const_tuple_int_pos_8_tuple;
PyObject *const_tuple_int_pos_9_tuple;
PyObject *const_tuple_none_none_tuple;
PyObject *const_str_plain_GEN1_I2C_SCL;
PyObject *const_str_plain_GEN1_I2C_SDA;
PyObject *const_str_plain_GEN2_I2C_SCL;
PyObject *const_str_plain_GEN2_I2C_SDA;
PyObject *const_str_plain_GPIO_EXP_P16;
PyObject *const_str_plain_GPIO_EXP_P17;
PyObject *const_str_plain_ORANGE_PI_PC;
PyObject *const_str_plain_ORANGE_PI_R1;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___compiled__;
PyObject *const_str_plain___internal__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain_has_location;
PyObject *const_str_plain_pull_up_down;
PyObject *const_str_plain_staticmethod;
PyObject *const_tuple_int_0_none_tuple;
PyObject *const_tuple_int_pos_10_tuple;
PyObject *const_tuple_int_pos_11_tuple;
PyObject *const_tuple_int_pos_12_tuple;
PyObject *const_tuple_int_pos_13_tuple;
PyObject *const_tuple_int_pos_14_tuple;
PyObject *const_tuple_int_pos_15_tuple;
PyObject *const_tuple_int_pos_16_tuple;
PyObject *const_tuple_int_pos_17_tuple;
PyObject *const_tuple_int_pos_18_tuple;
PyObject *const_tuple_int_pos_19_tuple;
PyObject *const_tuple_int_pos_20_tuple;
PyObject *const_tuple_int_pos_21_tuple;
PyObject *const_tuple_int_pos_24_tuple;
PyObject *const_tuple_int_pos_32_tuple;
PyObject *const_tuple_int_pos_64_tuple;
PyObject *const_tuple_str_chr_42_tuple;
PyObject *const_str_plain_CharlieBonnet;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain__initializing;
PyObject *const_str_plain_circuitpython;
PyObject *const_str_plain_readfrom_into;
PyObject *const_tuple_int_0_int_0_tuple;
PyObject *const_tuple_int_pos_116_tuple;
PyObject *const_tuple_str_plain_x_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain___orig_bases__;
PyObject *const_str_plain_any_beaglebone;
PyObject *const_str_plain_implementation;
PyObject *const_str_plain_write_readinto;
PyObject *const_str_plain___mro_entries__;
PyObject *const_str_plain_adafruit_blinka;
PyObject *const_str_plain_microcontroller;
PyObject *const_tuple_str_plain_Pin_tuple;
PyObject *const_str_plain_DRAGONBOARD_410C;
PyObject *const_str_plain_any_raspberry_pi;
PyObject *const_str_plain_get_device_model;
PyObject *const_tuple_none_none_none_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain___class_getitem__;
PyObject *const_str_plain_get_cpuinfo_field;
PyObject *const_tuple_int_0_int_pos_1_tuple;
PyObject *const_tuple_int_0_int_pos_2_tuple;
PyObject *const_tuple_int_0_int_pos_3_tuple;
PyObject *const_tuple_int_0_int_pos_4_tuple;
PyObject *const_tuple_int_0_int_pos_5_tuple;
PyObject *const_tuple_int_0_int_pos_6_tuple;
PyObject *const_tuple_int_0_int_pos_7_tuple;
PyObject *const_tuple_int_0_int_pos_8_tuple;
PyObject *const_tuple_int_0_int_pos_9_tuple;
PyObject *const_tuple_int_pos_1_int_0_tuple;
PyObject *const_tuple_int_pos_2_int_0_tuple;
PyObject *const_tuple_str_plain_sleep_tuple;
PyObject *const_str_plain_CORAL_EDGE_TPU_DEV;
PyObject *const_str_plain_any_embedded_linux;
PyObject *const_tuple_int_0_int_pos_10_tuple;
PyObject *const_tuple_int_0_int_pos_11_tuple;
PyObject *const_tuple_int_0_int_pos_12_tuple;
PyObject *const_tuple_int_0_int_pos_13_tuple;
PyObject *const_tuple_int_0_int_pos_14_tuple;
PyObject *const_tuple_int_0_none_int_0_tuple;
PyObject *const_str_plain_NotImplementedError;
PyObject *const_str_plain_adafruit_is31fl3731;
PyObject *const_str_plain_read_i2c_block_data;
PyObject *const_tuple_int_0_int_0_int_0_tuple;
PyObject *const_tuple_str_plain_DAP1_FS_tuple;
PyObject *const_tuple_str_plain_AUD_MCLK_tuple;
PyObject *const_tuple_str_plain_DAP1_DIN_tuple;
PyObject *const_tuple_str_plain_SPI1_CS0_tuple;
PyObject *const_tuple_str_plain_SPI1_CS1_tuple;
PyObject *const_tuple_str_plain_SPI1_SCK_tuple;
PyObject *const_str_plain_get_device_compatible;
PyObject *const_str_plain_writeto_then_readfrom;
PyObject *const_tuple_str_plain_DAP1_DOUT_tuple;
PyObject *const_tuple_str_plain_DAP1_SCLK_tuple;
PyObject *const_tuple_str_plain_SPI1_MISO_tuple;
PyObject *const_tuple_str_plain_SPI1_MOSI_tuple;
PyObject *const_tuple_str_plain_UART1_CTS_tuple;
PyObject *const_tuple_str_plain_UART1_RTS_tuple;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_str_plain_adafruit_platformdetect;
PyObject *const_str_plain_any_raspberry_pi_40_pin;
PyObject *const_tuple_int_0_none_int_0_none_tuple;
PyObject *const_tuple_str_plain_GEN1_I2C_SCL_tuple;
PyObject *const_tuple_str_plain_GEN1_I2C_SDA_tuple;
PyObject *const_tuple_str_plain_GEN2_I2C_SCL_tuple;
PyObject *const_tuple_str_plain_GEN2_I2C_SDA_tuple;
PyObject *const_tuple_str_plain_GPIO_EXP_P16_tuple;
PyObject *const_tuple_str_plain_GPIO_EXP_P17_tuple;
PyObject *const_str_plain_check_dt_compatible_value;
PyObject *const_str_plain_get_armbian_release_field;
PyObject *const_tuple_tuple_int_0_int_0_tuple_tuple;
PyObject *const_str_plain_submodule_search_locations;
PyObject *const_dict_8aeb909f6fefcf5760c5c4604f52a0cc;
PyObject *const_dict_bd9acfb6650818d787e11cf74e7981d1;
PyObject *const_tuple_str_plain_Pin_tuple_empty_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_1_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_2_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_3_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_4_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_5_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_6_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_7_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_8_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_9_tuple_tuple;
PyObject *const_str_plain_NUITKA_PACKAGE_adafruit_blinka;
PyObject *const_tuple_str_plain_self_str_plain_val_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_10_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_11_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_12_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_13_tuple_tuple;
PyObject *const_tuple_tuple_int_0_int_pos_14_tuple_tuple;
PyObject *const_tuple_str_plain_self_str_plain_attr_tuple;
PyObject *const_bytearray_7734633b10e3c30456916281c56d3a40;
PyObject *const_tuple_str_plain_self_str_plain_other_tuple;
PyObject *const_tuple_str_plain_self_str_plain_value_tuple;
PyObject *const_str_digest_0121c319bd84ff9d6a5138e9bbbd3657;
PyObject *const_str_digest_042902472e0ae572ba4bf463d0fc37cd;
PyObject *const_str_digest_050b893f9859457a2cb9a6e5acd06e19;
PyObject *const_str_digest_0c1898fc1f2c6d20fef19765d7f4025d;
PyObject *const_str_digest_0daddf6c4886f3926c22848feb4b084b;
PyObject *const_str_digest_0e0545f125585b80111045982f829c0c;
PyObject *const_str_digest_107b02ad77d67bbaaf288881f3e4530b;
PyObject *const_str_digest_169d01c053c9b40bcaa545433f06946e;
PyObject *const_str_digest_16a1f1b35028934e483cb53805cc0f5e;
PyObject *const_str_digest_1d1f43dfbb93e60d00ee0e787d075dd3;
PyObject *const_str_digest_204795fc719a5f4d79004b19ebaaa4f0;
PyObject *const_str_digest_2134f552f340f7ce0a8a355bdaa826fe;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_27590e9627cdd4999c774bf4c1f1962f;
PyObject *const_str_digest_2924342b5bc89f7a19a02b6ab2742f1e;
PyObject *const_str_digest_2ab60b4f55405026964a3306bc31e42a;
PyObject *const_str_digest_2c2105051be275e3a013884311f3861a;
PyObject *const_str_digest_35a61f90709e302b9e7a525c10ab66a6;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_461f5cb03aca48d6eb285a5f7999fc4a;
PyObject *const_str_digest_4dc5c42f81dddc562102970a99074af7;
PyObject *const_str_digest_4e256d114264995ca73901ec126f97c3;
PyObject *const_str_digest_4e7aad7c88b0724a830e614462e04cb4;
PyObject *const_str_digest_4ebeeb801387999c9452758cfcfb1249;
PyObject *const_str_digest_4fbae985f092f4091e6fdcac3426d015;
PyObject *const_str_digest_53178c0da82ef51e90b9f05eeb3d3a08;
PyObject *const_str_digest_53237157d5303abb9ce2918790913279;
PyObject *const_str_digest_58961c73026e70b23b08cf381b49e04e;
PyObject *const_str_digest_5b09d1d161877c85e90f4776974a2533;
PyObject *const_str_digest_5bfaf90dbd407b4fc29090c8f6415242;
PyObject *const_str_digest_61d3bd56be0becb53ea5a64883eefdcd;
PyObject *const_str_digest_64a851b331b809947b90aaf0f1eaaede;
PyObject *const_str_digest_6ef1c1de74d4522c07e3c7ee482b7a61;
PyObject *const_str_digest_6fba6dcdb09ebe74c73d220c28a4c8b9;
PyObject *const_str_digest_75fd71b1edada749c2ef7ac810062295;
PyObject *const_str_digest_7b1b39b143d57c01cb563cf6e2abebeb;
PyObject *const_str_digest_80a4805bdbd3485ea876d5c515fef787;
PyObject *const_str_digest_840781f3bcbba24c0c9d94a22c7c54d4;
PyObject *const_str_digest_8a90b7bc90ab321ed5fdeb2f8c407d36;
PyObject *const_str_digest_8eeb75553705ba0dd652b93d50f3a4ac;
PyObject *const_str_digest_96e349fb739b35937b0a66e566327387;
PyObject *const_str_digest_a92f659b27c80c84236371e5d850c570;
PyObject *const_str_digest_adb728c6c2e334e1f32698032cda0934;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_aeadebb446eb9697b49f22d96463f59a;
PyObject *const_str_digest_b26fd46e1b0aded1fdd3dde6bf5999b8;
PyObject *const_str_digest_b6c4491781143616325da56a91971a7c;
PyObject *const_str_digest_b7d128ea5b23af8ee5685b8834d9b56c;
PyObject *const_str_digest_c48e26755342fb3a8811b1a101a4718e;
PyObject *const_str_digest_c606d455df1b0b1ff46033ccb0d515a0;
PyObject *const_str_digest_cd071a97bd54c729d1fabb270c277385;
PyObject *const_str_digest_cea0edda4a37f9b21d5f316ef41250c8;
PyObject *const_str_digest_d0fff785ff78971c897b548f07ba60ad;
PyObject *const_str_digest_d1aaf6d901a3f894393de994d52a5367;
PyObject *const_str_digest_d5751cb219abc30399a2d639a5973dea;
PyObject *const_str_digest_efdbb1146d6752472c0f8c671fd9deb5;
PyObject *const_str_digest_f158e8772f2a5f3a55bc0908728823bc;
PyObject *const_str_digest_f25895fd22019cc3589993928699e319;
PyObject *const_str_digest_f46d0ef2d0a087f27969836562e28680;
PyObject *const_str_digest_f4a5b997d0b3c1411d2a276dc0aa3d6e;
PyObject *const_str_digest_f570069e0d46f80dd06443468800a290;
PyObject *const_str_digest_f593149bdea4cd8b2f0da587c0d8b83e;
PyObject *const_str_digest_fb6ee4778f1d62cd8875c5cfe7b93017;
PyObject *const_str_digest_fd4e498744c79a83acf09eec95362b39;
PyObject *const_str_digest_ff1a1456313d3e886477e5ceffe8c72d;
PyObject *const_tuple_str_plain_self_str_plain_pin_id_tuple;
PyObject *const_tuple_4056a0ef07ec9188d15ce9b607833855_tuple;
PyObject *const_tuple_495dd9d89d9634ae663598256e6465a5_tuple;
PyObject *const_tuple_6f70ce55669238251e7d6cf7fde5f256_tuple;
PyObject *const_tuple_8b75eea508b9ef665b6900efe85bbade_tuple;
PyObject *const_tuple_c5266559b4545301f11ca05d84cab86b_tuple;
PyObject *const_tuple_e6f453f188d84e241b37d93bda687549_tuple;
PyObject *const_tuple_fc0ac972cbd41df5dfec11db5338b333_tuple;
PyObject *const_tuple_str_plain_self_str_plain_detector_tuple;
PyObject *const_tuple_str_plain_self_str_plain_bcm_number_tuple;
PyObject *const_tuple_str_digest_53178c0da82ef51e90b9f05eeb3d3a08_tuple;
PyObject *const_tuple_str_digest_b26fd46e1b0aded1fdd3dde6bf5999b8_tuple;
PyObject *const_tuple_str_digest_f158e8772f2a5f3a55bc0908728823bc_tuple;
PyObject *const_tuple_str_plain_self_str_plain_mode_str_plain_pull_tuple;
PyObject *const_tuple_anon_function_anon_builtin_function_or_method_tuple;

static void _createGlobalConstants( void )
{
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong( 0ul );
    const_str_dot = UNSTREAM_STRING_ASCII( &constant_bin[ 54 ], 1, 0 );
    const_float_0_0 = UNSTREAM_FLOAT( &constant_bin[ 31396 ] );
    const_int_neg_1 = PyLong_FromLong( -1l );
    const_int_pos_1 = PyLong_FromUnsignedLong( 1ul );
    const_int_pos_2 = PyLong_FromUnsignedLong( 2ul );
    const_int_pos_3 = PyLong_FromUnsignedLong( 3ul );
    const_int_pos_4 = PyLong_FromUnsignedLong( 4ul );
    const_int_pos_5 = PyLong_FromUnsignedLong( 5ul );
    const_int_pos_6 = PyLong_FromUnsignedLong( 6ul );
    const_int_pos_7 = PyLong_FromUnsignedLong( 7ul );
    const_int_pos_8 = PyLong_FromUnsignedLong( 8ul );
    const_int_pos_9 = PyLong_FromUnsignedLong( 9ul );
    const_str_empty = UNSTREAM_STRING_ASCII( &constant_bin[ 0 ], 0, 0 );
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert( PyDict_Size( const_dict_empty ) == 0 );
    const_int_pos_10 = PyLong_FromUnsignedLong( 10ul );
    const_int_pos_11 = PyLong_FromUnsignedLong( 11ul );
    const_int_pos_12 = PyLong_FromUnsignedLong( 12ul );
    const_int_pos_13 = PyLong_FromUnsignedLong( 13ul );
    const_int_pos_14 = PyLong_FromUnsignedLong( 14ul );
    const_int_pos_15 = PyLong_FromUnsignedLong( 15ul );
    const_int_pos_16 = PyLong_FromUnsignedLong( 16ul );
    const_int_pos_17 = PyLong_FromUnsignedLong( 17ul );
    const_int_pos_18 = PyLong_FromUnsignedLong( 18ul );
    const_int_pos_19 = PyLong_FromUnsignedLong( 19ul );
    const_int_pos_20 = PyLong_FromUnsignedLong( 20ul );
    const_int_pos_21 = PyLong_FromUnsignedLong( 21ul );
    const_int_pos_22 = PyLong_FromUnsignedLong( 22ul );
    const_int_pos_23 = PyLong_FromUnsignedLong( 23ul );
    const_int_pos_24 = PyLong_FromUnsignedLong( 24ul );
    const_int_pos_25 = PyLong_FromUnsignedLong( 25ul );
    const_int_pos_26 = PyLong_FromUnsignedLong( 26ul );
    const_int_pos_27 = PyLong_FromUnsignedLong( 27ul );
    const_int_pos_32 = PyLong_FromUnsignedLong( 32ul );
    const_int_pos_33 = PyLong_FromUnsignedLong( 33ul );
    const_int_pos_35 = PyLong_FromUnsignedLong( 35ul );
    const_int_pos_36 = PyLong_FromUnsignedLong( 36ul );
    const_int_pos_37 = PyLong_FromUnsignedLong( 37ul );
    const_int_pos_39 = PyLong_FromUnsignedLong( 39ul );
    const_int_pos_46 = PyLong_FromUnsignedLong( 46ul );
    const_int_pos_59 = PyLong_FromUnsignedLong( 59ul );
    const_int_pos_60 = PyLong_FromUnsignedLong( 60ul );
    const_int_pos_63 = PyLong_FromUnsignedLong( 63ul );
    const_int_pos_64 = PyLong_FromUnsignedLong( 64ul );
    const_int_pos_65 = PyLong_FromUnsignedLong( 65ul );
    const_int_pos_66 = PyLong_FromUnsignedLong( 66ul );
    const_int_pos_67 = PyLong_FromUnsignedLong( 67ul );
    const_int_pos_68 = PyLong_FromUnsignedLong( 68ul );
    const_int_pos_69 = PyLong_FromUnsignedLong( 69ul );
    const_int_pos_70 = PyLong_FromUnsignedLong( 70ul );
    const_int_pos_71 = PyLong_FromUnsignedLong( 71ul );
    const_int_pos_72 = PyLong_FromUnsignedLong( 72ul );
    const_int_pos_73 = PyLong_FromUnsignedLong( 73ul );
    const_int_pos_74 = PyLong_FromUnsignedLong( 74ul );
    const_int_pos_75 = PyLong_FromUnsignedLong( 75ul );
    const_int_pos_76 = PyLong_FromUnsignedLong( 76ul );
    const_int_pos_77 = PyLong_FromUnsignedLong( 77ul );
    const_int_pos_78 = PyLong_FromUnsignedLong( 78ul );
    const_int_pos_79 = PyLong_FromUnsignedLong( 79ul );
    const_int_pos_80 = PyLong_FromUnsignedLong( 80ul );
    const_int_pos_81 = PyLong_FromUnsignedLong( 81ul );
    const_int_pos_82 = PyLong_FromUnsignedLong( 82ul );
    const_int_pos_83 = PyLong_FromUnsignedLong( 83ul );
    const_int_pos_84 = PyLong_FromUnsignedLong( 84ul );
    const_int_pos_85 = PyLong_FromUnsignedLong( 85ul );
    const_int_pos_86 = PyLong_FromUnsignedLong( 86ul );
    const_int_pos_87 = PyLong_FromUnsignedLong( 87ul );
    const_int_pos_88 = PyLong_FromUnsignedLong( 88ul );
    const_int_pos_89 = PyLong_FromUnsignedLong( 89ul );
    const_int_pos_90 = PyLong_FromUnsignedLong( 90ul );
    const_int_pos_91 = PyLong_FromUnsignedLong( 91ul );
    const_int_pos_92 = PyLong_FromUnsignedLong( 92ul );
    const_int_pos_93 = PyLong_FromUnsignedLong( 93ul );
    const_int_pos_94 = PyLong_FromUnsignedLong( 94ul );
    const_int_pos_95 = PyLong_FromUnsignedLong( 95ul );
    const_int_pos_96 = PyLong_FromUnsignedLong( 96ul );
    const_int_pos_97 = PyLong_FromUnsignedLong( 97ul );
    const_int_pos_98 = PyLong_FromUnsignedLong( 98ul );
    const_int_pos_99 = PyLong_FromUnsignedLong( 99ul );
    const_str_chr_42 = UNSTREAM_STRING_ASCII( &constant_bin[ 4795 ], 1, 0 );
    const_bytes_empty = UNSTREAM_BYTES( &constant_bin[ 0 ], 0 );
    const_int_pos_100 = PyLong_FromUnsignedLong( 100ul );
    const_int_pos_101 = PyLong_FromUnsignedLong( 101ul );
    const_int_pos_102 = PyLong_FromUnsignedLong( 102ul );
    const_int_pos_103 = PyLong_FromUnsignedLong( 103ul );
    const_int_pos_104 = PyLong_FromUnsignedLong( 104ul );
    const_int_pos_105 = PyLong_FromUnsignedLong( 105ul );
    const_int_pos_106 = PyLong_FromUnsignedLong( 106ul );
    const_int_pos_109 = PyLong_FromUnsignedLong( 109ul );
    const_int_pos_110 = PyLong_FromUnsignedLong( 110ul );
    const_int_pos_111 = PyLong_FromUnsignedLong( 111ul );
    const_int_pos_112 = PyLong_FromUnsignedLong( 112ul );
    const_int_pos_113 = PyLong_FromUnsignedLong( 113ul );
    const_int_pos_115 = PyLong_FromUnsignedLong( 115ul );
    const_int_pos_116 = PyLong_FromUnsignedLong( 116ul );
    const_int_pos_117 = PyLong_FromUnsignedLong( 117ul );
    const_int_pos_118 = PyLong_FromUnsignedLong( 118ul );
    const_int_pos_119 = PyLong_FromUnsignedLong( 119ul );
    const_int_pos_127 = PyLong_FromUnsignedLong( 127ul );
    const_int_pos_255 = PyLong_FromUnsignedLong( 255ul );
    const_str_newline = UNSTREAM_STRING_ASCII( &constant_bin[ 376 ], 1, 0 );
    const_str_plain__ = UNSTREAM_STRING_ASCII( &constant_bin[ 6 ], 1, 1 );
    const_str_plain_b = UNSTREAM_STRING_ASCII( &constant_bin[ 93 ], 1, 1 );
    const_str_plain_i = UNSTREAM_STRING_ASCII( &constant_bin[ 21 ], 1, 1 );
    const_str_plain_x = UNSTREAM_STRING_ASCII( &constant_bin[ 170 ], 1, 1 );
    const_str_plain_y = UNSTREAM_STRING_ASCII( &constant_bin[ 56 ], 1, 1 );
    const_tuple_empty = PyTuple_New( 0 );
    const_str_plain_A0 = UNSTREAM_STRING_ASCII( &constant_bin[ 6547 ], 2, 1 );
    const_str_plain_A2 = UNSTREAM_STRING_ASCII( &constant_bin[ 6540 ], 2, 1 );
    const_str_plain_A4 = UNSTREAM_STRING_ASCII( &constant_bin[ 20041 ], 2, 1 );
    const_str_plain_A5 = UNSTREAM_STRING_ASCII( &constant_bin[ 19570 ], 2, 1 );
    const_str_plain_A6 = UNSTREAM_STRING_ASCII( &constant_bin[ 6689 ], 2, 1 );
    const_str_plain_D2 = UNSTREAM_STRING_ASCII( &constant_bin[ 9007 ], 2, 1 );
    const_str_plain_IN = UNSTREAM_STRING_ASCII( &constant_bin[ 1082 ], 2, 1 );
    const_str_plain_id = UNSTREAM_STRING_ASCII( &constant_bin[ 510 ], 2, 1 );
    const_str_plain_os = UNSTREAM_STRING_ASCII( &constant_bin[ 1648 ], 2, 1 );
    const_str_plain_rb = UNSTREAM_STRING_ASCII( &constant_bin[ 31404 ], 2, 1 );
    const_str_plain_H07 = UNSTREAM_STRING_ASCII( &constant_bin[ 31406 ], 3, 1 );
    const_str_plain_I2C = UNSTREAM_STRING_ASCII( &constant_bin[ 162 ], 3, 1 );
    const_str_plain_J04 = UNSTREAM_STRING_ASCII( &constant_bin[ 31409 ], 3, 1 );
    const_str_plain_J05 = UNSTREAM_STRING_ASCII( &constant_bin[ 31412 ], 3, 1 );
    const_str_plain_J06 = UNSTREAM_STRING_ASCII( &constant_bin[ 31415 ], 3, 1 );
    const_str_plain_LOW = UNSTREAM_STRING_ASCII( &constant_bin[ 31418 ], 3, 1 );
    const_str_plain_MSB = UNSTREAM_STRING_ASCII( &constant_bin[ 31421 ], 3, 1 );
    const_str_plain_OUT = UNSTREAM_STRING_ASCII( &constant_bin[ 4179 ], 3, 1 );
    const_str_plain_P16 = UNSTREAM_STRING_ASCII( &constant_bin[ 31424 ], 3, 1 );
    const_str_plain_P17 = UNSTREAM_STRING_ASCII( &constant_bin[ 31427 ], 3, 1 );
    const_str_plain_PC0 = UNSTREAM_STRING_ASCII( &constant_bin[ 31430 ], 3, 1 );
    const_str_plain_Pin = UNSTREAM_STRING_ASCII( &constant_bin[ 5371 ], 3, 1 );
    const_str_plain_SCL = UNSTREAM_STRING_ASCII( &constant_bin[ 9085 ], 3, 1 );
    const_str_plain_SDA = UNSTREAM_STRING_ASCII( &constant_bin[ 11167 ], 3, 1 );
    const_str_plain_SPI = UNSTREAM_STRING_ASCII( &constant_bin[ 6910 ], 3, 1 );
    const_str_plain_bit = UNSTREAM_STRING_ASCII( &constant_bin[ 10909 ], 3, 1 );
    const_str_plain_buf = UNSTREAM_STRING_ASCII( &constant_bin[ 629 ], 3, 1 );
    const_str_plain_end = UNSTREAM_STRING_ASCII( &constant_bin[ 537 ], 3, 1 );
    const_str_plain_get = UNSTREAM_STRING_ASCII( &constant_bin[ 9868 ], 3, 1 );
    const_str_plain_i2c = UNSTREAM_STRING_ASCII( &constant_bin[ 191 ], 3, 1 );
    const_str_plain_int = UNSTREAM_STRING_ASCII( &constant_bin[ 105 ], 3, 1 );
    const_str_plain_key = UNSTREAM_STRING_ASCII( &constant_bin[ 4913 ], 3, 1 );
    const_str_plain_len = UNSTREAM_STRING_ASCII( &constant_bin[ 187 ], 3, 1 );
    const_str_plain_reg = UNSTREAM_STRING_ASCII( &constant_bin[ 765 ], 3, 1 );
    const_str_plain_sck = UNSTREAM_STRING_ASCII( &constant_bin[ 31433 ], 3, 1 );
    const_str_plain_sum = UNSTREAM_STRING_ASCII( &constant_bin[ 4218 ], 3, 1 );
    const_str_plain_sys = UNSTREAM_STRING_ASCII( &constant_bin[ 4985 ], 3, 1 );
    const_str_plain_val = UNSTREAM_STRING_ASCII( &constant_bin[ 181 ], 3, 1 );
    const_int_pos_100000 = PyLong_FromUnsignedLong( 100000ul );
    const_str_plain_AA00 = UNSTREAM_STRING_ASCII( &constant_bin[ 31436 ], 4, 1 );
    const_str_plain_AA01 = UNSTREAM_STRING_ASCII( &constant_bin[ 31440 ], 4, 1 );
    const_str_plain_AA02 = UNSTREAM_STRING_ASCII( &constant_bin[ 31444 ], 4, 1 );
    const_str_plain_BB00 = UNSTREAM_STRING_ASCII( &constant_bin[ 31448 ], 4, 1 );
    const_str_plain_Chip = UNSTREAM_STRING_ASCII( &constant_bin[ 23169 ], 4, 1 );
    const_str_plain_Enum = UNSTREAM_STRING_ASCII( &constant_bin[ 4605 ], 4, 1 );
    const_str_plain_GPIO = UNSTREAM_STRING_ASCII( &constant_bin[ 7869 ], 4, 1 );
    const_str_plain_HIGH = UNSTREAM_STRING_ASCII( &constant_bin[ 31452 ], 4, 1 );
    const_str_plain_MISO = UNSTREAM_STRING_ASCII( &constant_bin[ 9010 ], 4, 1 );
    const_str_plain_MOSI = UNSTREAM_STRING_ASCII( &constant_bin[ 9095 ], 4, 1 );
    const_str_plain_None = UNSTREAM_STRING_ASCII( &constant_bin[ 16083 ], 4, 1 );
    const_str_plain_PA14 = UNSTREAM_STRING_ASCII( &constant_bin[ 31456 ], 4, 1 );
    const_str_plain_PA15 = UNSTREAM_STRING_ASCII( &constant_bin[ 31460 ], 4, 1 );
    const_str_plain_PA16 = UNSTREAM_STRING_ASCII( &constant_bin[ 31464 ], 4, 1 );
    const_str_plain_PWM1 = UNSTREAM_STRING_ASCII( &constant_bin[ 7119 ], 4, 1 );
    const_str_plain_PWM2 = UNSTREAM_STRING_ASCII( &constant_bin[ 7194 ], 4, 1 );
    const_str_plain_PWM3 = UNSTREAM_STRING_ASCII( &constant_bin[ 31468 ], 4, 1 );
    const_str_plain_S805 = UNSTREAM_STRING_ASCII( &constant_bin[ 31472 ], 4, 1 );
    const_str_plain_S905 = UNSTREAM_STRING_ASCII( &constant_bin[ 31476 ], 4, 1 );
    const_str_plain_T186 = UNSTREAM_STRING_ASCII( &constant_bin[ 31480 ], 4, 1 );
    const_str_plain_T194 = UNSTREAM_STRING_ASCII( &constant_bin[ 31484 ], 4, 1 );
    const_str_plain_T210 = UNSTREAM_STRING_ASCII( &constant_bin[ 31488 ], 4, 1 );
    const_str_plain__spi = UNSTREAM_STRING_ASCII( &constant_bin[ 31492 ], 4, 1 );
    const_str_plain_addr = UNSTREAM_STRING_ASCII( &constant_bin[ 597 ], 4, 1 );
    const_str_plain_attr = UNSTREAM_STRING_ASCII( &constant_bin[ 4250 ], 4, 1 );
    const_str_plain_bits = UNSTREAM_STRING_ASCII( &constant_bin[ 10909 ], 4, 1 );
    const_str_plain_chip = UNSTREAM_STRING_ASCII( &constant_bin[ 10378 ], 4, 1 );
    const_str_plain_data = UNSTREAM_STRING_ASCII( &constant_bin[ 98 ], 4, 1 );
    const_str_plain_file = UNSTREAM_STRING_ASCII( &constant_bin[ 185 ], 4, 1 );
    const_str_plain_init = UNSTREAM_STRING_ASCII( &constant_bin[ 48 ], 4, 1 );
    const_str_plain_iter = UNSTREAM_STRING_ASCII( &constant_bin[ 4477 ], 4, 1 );
    const_str_plain_join = UNSTREAM_STRING_ASCII( &constant_bin[ 31496 ], 4, 1 );
    const_str_plain_line = UNSTREAM_STRING_ASCII( &constant_bin[ 10174 ], 4, 1 );
    const_str_plain_miso = UNSTREAM_STRING_ASCII( &constant_bin[ 10922 ], 4, 1 );
    const_str_plain_mode = UNSTREAM_STRING_ASCII( &constant_bin[ 18221 ], 4, 1 );
    const_str_plain_mosi = UNSTREAM_STRING_ASCII( &constant_bin[ 10619 ], 4, 1 );
    const_str_plain_name = UNSTREAM_STRING_ASCII( &constant_bin[ 5863 ], 4, 1 );
    const_str_plain_nano = UNSTREAM_STRING_ASCII( &constant_bin[ 31500 ], 4, 1 );
    const_str_plain_open = UNSTREAM_STRING_ASCII( &constant_bin[ 1513 ], 4, 1 );
    const_str_plain_path = UNSTREAM_STRING_ASCII( &constant_bin[ 4306 ], 4, 1 );
    const_str_plain_pull = UNSTREAM_STRING_ASCII( &constant_bin[ 10224 ], 4, 1 );
    const_str_plain_read = UNSTREAM_STRING_ASCII( &constant_bin[ 123 ], 4, 1 );
    const_str_plain_repr = UNSTREAM_STRING_ASCII( &constant_bin[ 491 ], 4, 1 );
    const_str_plain_scan = UNSTREAM_STRING_ASCII( &constant_bin[ 31504 ], 4, 1 );
    const_str_plain_self = UNSTREAM_STRING_ASCII( &constant_bin[ 31508 ], 4, 1 );
    const_str_plain_send = UNSTREAM_STRING_ASCII( &constant_bin[ 536 ], 4, 1 );
    const_str_plain_site = UNSTREAM_STRING_ASCII( &constant_bin[ 31512 ], 4, 1 );
    const_str_plain_stop = UNSTREAM_STRING_ASCII( &constant_bin[ 17297 ], 4, 1 );
    const_str_plain_time = UNSTREAM_STRING_ASCII( &constant_bin[ 3834 ], 4, 1 );
    const_str_plain_type = UNSTREAM_STRING_ASCII( &constant_bin[ 645 ], 4, 1 );
    const_float_minus_0_0 = UNSTREAM_FLOAT( &constant_bin[ 31516 ] );
    const_str_plain_Board = UNSTREAM_STRING_ASCII( &constant_bin[ 19743 ], 5, 1 );
    const_str_plain_False = UNSTREAM_STRING_ASCII( &constant_bin[ 5114 ], 5, 1 );
    const_str_plain_SAMA5 = UNSTREAM_STRING_ASCII( &constant_bin[ 31524 ], 5, 1 );
    const_str_plain_SCL_1 = UNSTREAM_STRING_ASCII( &constant_bin[ 31529 ], 5, 1 );
    const_str_plain_SDA_1 = UNSTREAM_STRING_ASCII( &constant_bin[ 31534 ], 5, 1 );
    const_str_plain_SMBus = UNSTREAM_STRING_ASCII( &constant_bin[ 81 ], 5, 1 );
    const_str_plain_STM32 = UNSTREAM_STRING_ASCII( &constant_bin[ 13254 ], 5, 1 );
    const_str_plain_SUN8I = UNSTREAM_STRING_ASCII( &constant_bin[ 31539 ], 5, 1 );
    const_str_plain__mode = UNSTREAM_STRING_ASCII( &constant_bin[ 18220 ], 5, 1 );
    const_str_plain_blink = UNSTREAM_STRING_ASCII( &constant_bin[ 4420 ], 5, 1 );
    const_str_plain_board = UNSTREAM_STRING_ASCII( &constant_bin[ 5460 ], 5, 1 );
    const_str_plain_busio = UNSTREAM_STRING_ASCII( &constant_bin[ 30419 ], 5, 1 );
    const_str_plain_bytes = UNSTREAM_STRING_ASCII( &constant_bin[ 799 ], 5, 1 );
    const_str_plain_clock = UNSTREAM_STRING_ASCII( &constant_bin[ 3856 ], 5, 1 );
    const_str_plain_close = UNSTREAM_STRING_ASCII( &constant_bin[ 1646 ], 5, 1 );
    const_str_plain_const = UNSTREAM_STRING_ASCII( &constant_bin[ 20235 ], 5, 1 );
    const_str_plain_count = UNSTREAM_STRING_ASCII( &constant_bin[ 2148 ], 5, 1 );
    const_str_plain_flags = UNSTREAM_STRING_ASCII( &constant_bin[ 616 ], 5, 1 );
    const_str_plain_input = UNSTREAM_STRING_ASCII( &constant_bin[ 31544 ], 5, 1 );
    const_str_plain_items = UNSTREAM_STRING_ASCII( &constant_bin[ 4481 ], 5, 1 );
    const_str_plain_level = UNSTREAM_STRING_ASCII( &constant_bin[ 16939 ], 5, 1 );
    const_str_plain_model = UNSTREAM_STRING_ASCII( &constant_bin[ 18545 ], 5, 1 );
    const_str_plain_other = UNSTREAM_STRING_ASCII( &constant_bin[ 1729 ], 5, 1 );
    const_str_plain_phase = UNSTREAM_STRING_ASCII( &constant_bin[ 31549 ], 5, 1 );
    const_str_plain_pixel = UNSTREAM_STRING_ASCII( &constant_bin[ 14995 ], 5, 1 );
    const_str_plain_print = UNSTREAM_STRING_ASCII( &constant_bin[ 3892 ], 5, 1 );
    const_str_plain_quill = UNSTREAM_STRING_ASCII( &constant_bin[ 31554 ], 5, 1 );
    const_str_plain_range = UNSTREAM_STRING_ASCII( &constant_bin[ 15715 ], 5, 1 );
    const_str_plain_setup = UNSTREAM_STRING_ASCII( &constant_bin[ 31559 ], 5, 1 );
    const_str_plain_sleep = UNSTREAM_STRING_ASCII( &constant_bin[ 16801 ], 5, 1 );
    const_str_plain_start = UNSTREAM_STRING_ASCII( &constant_bin[ 6045 ], 5, 1 );
    const_str_plain_tegra = UNSTREAM_STRING_ASCII( &constant_bin[ 13280 ], 5, 1 );
    const_str_plain_throw = UNSTREAM_STRING_ASCII( &constant_bin[ 31564 ], 5, 1 );
    const_str_plain_tuple = UNSTREAM_STRING_ASCII( &constant_bin[ 478 ], 5, 1 );
    const_str_plain_types = UNSTREAM_STRING_ASCII( &constant_bin[ 645 ], 5, 1 );
    const_str_plain_utime = UNSTREAM_STRING_ASCII( &constant_bin[ 31569 ], 5, 1 );
    const_str_plain_value = UNSTREAM_STRING_ASCII( &constant_bin[ 605 ], 5, 1 );
    const_str_plain_write = UNSTREAM_STRING_ASCII( &constant_bin[ 87 ], 5, 1 );
    const_str_plain_AM33XX = UNSTREAM_STRING_ASCII( &constant_bin[ 31574 ], 6, 1 );
    const_str_plain_FT232H = UNSTREAM_STRING_ASCII( &constant_bin[ 21860 ], 6, 1 );
    const_str_plain_HFU540 = UNSTREAM_STRING_ASCII( &constant_bin[ 31580 ], 6, 1 );
    const_str_plain_IMX8MX = UNSTREAM_STRING_ASCII( &constant_bin[ 31586 ], 6, 1 );
    const_str_plain_MASTER = UNSTREAM_STRING_ASCII( &constant_bin[ 31592 ], 6, 1 );
    const_str_plain_PUD_UP = UNSTREAM_STRING_ASCII( &constant_bin[ 31598 ], 6, 1 );
    const_str_plain_SAMD21 = UNSTREAM_STRING_ASCII( &constant_bin[ 31604 ], 6, 1 );
    const_str_plain___eq__ = UNSTREAM_STRING_ASCII( &constant_bin[ 24711 ], 6, 1 );
    const_str_plain__value = UNSTREAM_STRING_ASCII( &constant_bin[ 10059 ], 6, 1 );
    const_str_plain_append = UNSTREAM_STRING_ASCII( &constant_bin[ 31610 ], 6, 1 );
    const_str_plain_atexit = UNSTREAM_STRING_ASCII( &constant_bin[ 31616 ], 6, 1 );
    const_str_plain_buffer = UNSTREAM_STRING_ASCII( &constant_bin[ 629 ], 6, 1 );
    const_str_plain_deinit = UNSTREAM_STRING_ASCII( &constant_bin[ 4026 ], 6, 1 );
    const_str_plain_format = UNSTREAM_STRING_ASCII( &constant_bin[ 31622 ], 6, 1 );
    const_str_plain_in_end = UNSTREAM_STRING_ASCII( &constant_bin[ 31628 ], 6, 1 );
    const_str_plain_locals = UNSTREAM_STRING_ASCII( &constant_bin[ 24951 ], 6, 1 );
    const_str_plain_object = UNSTREAM_STRING_ASCII( &constant_bin[ 4516 ], 6, 1 );
    const_str_plain_origin = UNSTREAM_STRING_ASCII( &constant_bin[ 24474 ], 6, 1 );
    const_str_plain_output = UNSTREAM_STRING_ASCII( &constant_bin[ 31634 ], 6, 1 );
    const_str_plain_pin_id = UNSTREAM_STRING_ASCII( &constant_bin[ 31640 ], 6, 1 );
    const_str_plain_result = UNSTREAM_STRING_ASCII( &constant_bin[ 27896 ], 6, 1 );
    const_str_plain_unlock = UNSTREAM_STRING_ASCII( &constant_bin[ 4471 ], 6, 1 );
    const_str_plain_xavier = UNSTREAM_STRING_ASCII( &constant_bin[ 31646 ], 6, 1 );
    const_tuple_none_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    const_tuple_true_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_true_tuple, 0, Py_True ); Py_INCREF( Py_True );
    const_str_plain_APQ8016 = UNSTREAM_STRING_ASCII( &constant_bin[ 31652 ], 7, 1 );
    const_str_plain_BCM2XXX = UNSTREAM_STRING_ASCII( &constant_bin[ 31659 ], 7, 1 );
    const_str_plain_DAP1_FS = UNSTREAM_STRING_ASCII( &constant_bin[ 31666 ], 7, 1 );
    const_str_plain_ESP8266 = UNSTREAM_STRING_ASCII( &constant_bin[ 5537 ], 7, 1 );
    const_str_plain_PULL_UP = UNSTREAM_STRING_ASCII( &constant_bin[ 31673 ], 7, 1 );
    const_str_plain_SPI0_CS = UNSTREAM_STRING_ASCII( &constant_bin[ 7298 ], 7, 1 );
    const_str_plain___all__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31680 ], 7, 1 );
    const_str_plain___cmp__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31687 ], 7, 1 );
    const_str_plain___doc__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31694 ], 7, 1 );
    const_str_plain__locked = UNSTREAM_STRING_ASCII( &constant_bin[ 31701 ], 7, 1 );
    const_str_plain_address = UNSTREAM_STRING_ASCII( &constant_bin[ 597 ], 7, 1 );
    const_str_plain_ap_chip = UNSTREAM_STRING_ASCII( &constant_bin[ 31708 ], 7, 1 );
    const_str_plain_chip_id = UNSTREAM_STRING_ASCII( &constant_bin[ 31715 ], 7, 1 );
    const_str_plain_cleanup = UNSTREAM_STRING_ASCII( &constant_bin[ 31722 ], 7, 1 );
    const_str_plain_compile = UNSTREAM_STRING_ASCII( &constant_bin[ 31729 ], 7, 1 );
    const_str_plain_dirname = UNSTREAM_STRING_ASCII( &constant_bin[ 31736 ], 7, 1 );
    const_str_plain_environ = UNSTREAM_STRING_ASCII( &constant_bin[ 5597 ], 7, 1 );
    const_str_plain_esp8266 = UNSTREAM_STRING_ASCII( &constant_bin[ 9191 ], 7, 1 );
    const_str_plain_globals = UNSTREAM_STRING_ASCII( &constant_bin[ 31743 ], 7, 1 );
    const_str_plain_inspect = UNSTREAM_STRING_ASCII( &constant_bin[ 31750 ], 7, 1 );
    const_str_plain_out_end = UNSTREAM_STRING_ASCII( &constant_bin[ 31757 ], 7, 1 );
    const_str_plain_pwmOuts = UNSTREAM_STRING_ASCII( &constant_bin[ 31764 ], 7, 1 );
    const_str_plain_request = UNSTREAM_STRING_ASCII( &constant_bin[ 31771 ], 7, 1 );
    const_str_plain_setmode = UNSTREAM_STRING_ASCII( &constant_bin[ 31778 ], 7, 1 );
    const_str_plain_writeto = UNSTREAM_STRING_ASCII( &constant_bin[ 9735 ], 7, 1 );
    const_tuple_false_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_false_tuple, 0, Py_False ); Py_INCREF( Py_False );
    const_tuple_int_0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    const_str_angle_listcomp = UNSTREAM_STRING_ASCII( &constant_bin[ 31785 ], 10, 0 );
    const_str_plain_AUD_MCLK = UNSTREAM_STRING_ASCII( &constant_bin[ 31795 ], 8, 1 );
    const_str_plain_DAP1_DIN = UNSTREAM_STRING_ASCII( &constant_bin[ 31803 ], 8, 1 );
    const_str_plain_Detector = UNSTREAM_STRING_ASCII( &constant_bin[ 18486 ], 8, 1 );
    const_str_plain_I2C0_SCL = UNSTREAM_STRING_ASCII( &constant_bin[ 31811 ], 8, 1 );
    const_str_plain_I2C0_SDA = UNSTREAM_STRING_ASCII( &constant_bin[ 31819 ], 8, 1 );
    const_str_plain_I2C1_SCL = UNSTREAM_STRING_ASCII( &constant_bin[ 31827 ], 8, 1 );
    const_str_plain_I2C1_SDA = UNSTREAM_STRING_ASCII( &constant_bin[ 31835 ], 8, 1 );
    const_str_plain_I2C2_SCL = UNSTREAM_STRING_ASCII( &constant_bin[ 31843 ], 8, 1 );
    const_str_plain_I2C2_SDA = UNSTREAM_STRING_ASCII( &constant_bin[ 31851 ], 8, 1 );
    const_str_plain_Lockable = UNSTREAM_STRING_ASCII( &constant_bin[ 4462 ], 8, 1 );
    const_str_plain_PUD_DOWN = UNSTREAM_STRING_ASCII( &constant_bin[ 31859 ], 8, 1 );
    const_str_plain_SPI1_CS0 = UNSTREAM_STRING_ASCII( &constant_bin[ 14156 ], 8, 1 );
    const_str_plain_SPI1_CS1 = UNSTREAM_STRING_ASCII( &constant_bin[ 14045 ], 8, 1 );
    const_str_plain_SPI1_SCK = UNSTREAM_STRING_ASCII( &constant_bin[ 31867 ], 8, 1 );
    const_str_plain_TWI0_SCL = UNSTREAM_STRING_ASCII( &constant_bin[ 31875 ], 8, 1 );
    const_str_plain_TWI0_SDA = UNSTREAM_STRING_ASCII( &constant_bin[ 31883 ], 8, 1 );
    const_str_plain_UART1_RX = UNSTREAM_STRING_ASCII( &constant_bin[ 6990 ], 8, 1 );
    const_str_plain_UART1_TX = UNSTREAM_STRING_ASCII( &constant_bin[ 7074 ], 8, 1 );
    const_str_plain_UART2_RX = UNSTREAM_STRING_ASCII( &constant_bin[ 7634 ], 8, 1 );
    const_str_plain_UART2_TX = UNSTREAM_STRING_ASCII( &constant_bin[ 7409 ], 8, 1 );
    const_str_plain___dict__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31891 ], 8, 1 );
    const_str_plain___exit__ = UNSTREAM_STRING_ASCII( &constant_bin[ 854 ], 8, 1 );
    const_str_plain___file__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31899 ], 8, 1 );
    const_str_plain___init__ = UNSTREAM_STRING_ASCII( &constant_bin[ 46 ], 8, 1 );
    const_str_plain___iter__ = UNSTREAM_STRING_ASCII( &constant_bin[ 26037 ], 8, 1 );
    const_str_plain___main__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31907 ], 8, 1 );
    const_str_plain___name__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31915 ], 8, 1 );
    const_str_plain___path__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31923 ], 8, 1 );
    const_str_plain___repr__ = UNSTREAM_STRING_ASCII( &constant_bin[ 5229 ], 8, 1 );
    const_str_plain___spec__ = UNSTREAM_STRING_ASCII( &constant_bin[ 31931 ], 8, 1 );
    const_str_plain_agnostic = UNSTREAM_STRING_ASCII( &constant_bin[ 5277 ], 8, 1 );
    const_str_plain_baudrate = UNSTREAM_STRING_ASCII( &constant_bin[ 9914 ], 8, 1 );
    const_str_plain_board_id = UNSTREAM_STRING_ASCII( &constant_bin[ 31939 ], 8, 1 );
    const_str_plain_detector = UNSTREAM_STRING_ASCII( &constant_bin[ 31947 ], 8, 1 );
    const_str_plain_exc_type = UNSTREAM_STRING_ASCII( &constant_bin[ 31955 ], 8, 1 );
    const_str_plain_firstbit = UNSTREAM_STRING_ASCII( &constant_bin[ 31963 ], 8, 1 );
    const_str_plain_fromlist = UNSTREAM_STRING_ASCII( &constant_bin[ 31971 ], 8, 1 );
    const_str_plain_i2cPorts = UNSTREAM_STRING_ASCII( &constant_bin[ 31979 ], 8, 1 );
    const_str_plain_in_start = UNSTREAM_STRING_ASCII( &constant_bin[ 31987 ], 8, 1 );
    const_str_plain_platform = UNSTREAM_STRING_ASCII( &constant_bin[ 5055 ], 8, 1 );
    const_str_plain_polarity = UNSTREAM_STRING_ASCII( &constant_bin[ 31995 ], 8, 1 );
    const_str_plain_property = UNSTREAM_STRING_ASCII( &constant_bin[ 32003 ], 8, 1 );
    const_str_plain_readinto = UNSTREAM_STRING_ASCII( &constant_bin[ 30932 ], 8, 1 );
    const_str_plain_register = UNSTREAM_STRING_ASCII( &constant_bin[ 765 ], 8, 1 );
    const_str_plain_spiPorts = UNSTREAM_STRING_ASCII( &constant_bin[ 32011 ], 8, 1 );
    const_str_plain_try_lock = UNSTREAM_STRING_ASCII( &constant_bin[ 4971 ], 8, 1 );
    const_str_angle_metaclass = UNSTREAM_STRING_ASCII( &constant_bin[ 32019 ], 11, 0 );
    const_str_plain_DAP1_DOUT = UNSTREAM_STRING_ASCII( &constant_bin[ 32030 ], 9, 1 );
    const_str_plain_DAP1_SCLK = UNSTREAM_STRING_ASCII( &constant_bin[ 32039 ], 9, 1 );
    const_str_plain_I2C_PORTS = UNSTREAM_STRING_ASCII( &constant_bin[ 32048 ], 9, 1 );
    const_str_plain_ODROID_C2 = UNSTREAM_STRING_ASCII( &constant_bin[ 32057 ], 9, 1 );
    const_str_plain_PULL_DOWN = UNSTREAM_STRING_ASCII( &constant_bin[ 32066 ], 9, 1 );
    const_str_plain_PULL_NONE = UNSTREAM_STRING_ASCII( &constant_bin[ 32075 ], 9, 1 );
    const_str_plain_SPI0_MISO = UNSTREAM_STRING_ASCII( &constant_bin[ 32084 ], 9, 1 );
    const_str_plain_SPI0_MOSI = UNSTREAM_STRING_ASCII( &constant_bin[ 32093 ], 9, 1 );
    const_str_plain_SPI0_SCLK = UNSTREAM_STRING_ASCII( &constant_bin[ 32102 ], 9, 1 );
    const_str_plain_SPI1_MISO = UNSTREAM_STRING_ASCII( &constant_bin[ 11131 ], 9, 1 );
    const_str_plain_SPI1_MOSI = UNSTREAM_STRING_ASCII( &constant_bin[ 11185 ], 9, 1 );
    const_str_plain_SPI1_SCLK = UNSTREAM_STRING_ASCII( &constant_bin[ 11142 ], 9, 1 );
    const_str_plain_SPI_PORTS = UNSTREAM_STRING_ASCII( &constant_bin[ 32111 ], 9, 1 );
    const_str_plain_TEGRA_SOC = UNSTREAM_STRING_ASCII( &constant_bin[ 32120 ], 9, 1 );
    const_str_plain_UART1_CTS = UNSTREAM_STRING_ASCII( &constant_bin[ 7325 ], 9, 1 );
    const_str_plain_UART1_RTS = UNSTREAM_STRING_ASCII( &constant_bin[ 7218 ], 9, 1 );
    const_str_plain___class__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32129 ], 9, 1 );
    const_str_plain___debug__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32138 ], 9, 1 );
    const_str_plain___enter__ = UNSTREAM_STRING_ASCII( &constant_bin[ 2910 ], 9, 1 );
    const_str_plain_buffer_in = UNSTREAM_STRING_ASCII( &constant_bin[ 32147 ], 9, 1 );
    const_str_plain_bytearray = UNSTREAM_STRING_ASCII( &constant_bin[ 839 ], 9, 1 );
    const_str_plain_exc_value = UNSTREAM_STRING_ASCII( &constant_bin[ 32156 ], 9, 1 );
    const_str_plain_metaclass = UNSTREAM_STRING_ASCII( &constant_bin[ 32020 ], 9, 1 );
    const_str_plain_out_start = UNSTREAM_STRING_ASCII( &constant_bin[ 32165 ], 9, 1 );
    const_str_plain_read_byte = UNSTREAM_STRING_ASCII( &constant_bin[ 297 ], 9, 1 );
    const_str_plain_traceback = UNSTREAM_STRING_ASCII( &constant_bin[ 32174 ], 9, 1 );
    const_str_plain_uartPorts = UNSTREAM_STRING_ASCII( &constant_bin[ 32183 ], 9, 1 );
    const_str_plain_UART_PORTS = UNSTREAM_STRING_ASCII( &constant_bin[ 32192 ], 10, 1 );
    const_str_plain___cached__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32202 ], 10, 1 );
    const_str_plain___import__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32212 ], 10, 1 );
    const_str_plain___loader__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32222 ], 10, 1 );
    const_str_plain___module__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32232 ], 10, 1 );
    const_str_plain_bcm_number = UNSTREAM_STRING_ASCII( &constant_bin[ 32242 ], 10, 1 );
    const_str_plain_buffer_out = UNSTREAM_STRING_ASCII( &constant_bin[ 32252 ], 10, 1 );
    const_str_plain_read_bytes = UNSTREAM_STRING_ASCII( &constant_bin[ 2423 ], 10, 1 );
    const_str_plain_GENERIC_X86 = UNSTREAM_STRING_ASCII( &constant_bin[ 32262 ], 11, 1 );
    const_str_plain_GIANT_BOARD = UNSTREAM_STRING_ASCII( &constant_bin[ 32273 ], 11, 1 );
    const_str_plain___getattr__ = UNSTREAM_STRING_ASCII( &constant_bin[ 19936 ], 11, 1 );
    const_str_plain___getitem__ = UNSTREAM_STRING_ASCII( &constant_bin[ 26073 ], 11, 1 );
    const_str_plain___package__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32284 ], 11, 1 );
    const_str_plain___prepare__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32295 ], 11, 1 );
    const_str_plain_classmethod = UNSTREAM_STRING_ASCII( &constant_bin[ 32306 ], 11, 1 );
    const_str_plain_micropython = UNSTREAM_STRING_ASCII( &constant_bin[ 31362 ], 11, 1 );
    const_str_plain_setwarnings = UNSTREAM_STRING_ASCII( &constant_bin[ 32317 ], 11, 1 );
    const_str_plain_write_bytes = UNSTREAM_STRING_ASCII( &constant_bin[ 2765 ], 11, 1 );
    const_str_plain_write_value = UNSTREAM_STRING_ASCII( &constant_bin[ 32328 ], 11, 1 );
    const_tuple_int_pos_1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_int_pos_2_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_2_tuple, 0, const_int_pos_2 ); Py_INCREF( const_int_pos_2 );
    const_tuple_int_pos_3_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_3_tuple, 0, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    const_tuple_int_pos_4_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_4_tuple, 0, const_int_pos_4 ); Py_INCREF( const_int_pos_4 );
    const_tuple_int_pos_5_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_5_tuple, 0, const_int_pos_5 ); Py_INCREF( const_int_pos_5 );
    const_tuple_int_pos_6_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_6_tuple, 0, const_int_pos_6 ); Py_INCREF( const_int_pos_6 );
    const_tuple_int_pos_7_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_7_tuple, 0, const_int_pos_7 ); Py_INCREF( const_int_pos_7 );
    const_tuple_int_pos_8_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_8_tuple, 0, const_int_pos_8 ); Py_INCREF( const_int_pos_8 );
    const_tuple_int_pos_9_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_9_tuple, 0, const_int_pos_9 ); Py_INCREF( const_int_pos_9 );
    const_tuple_none_none_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    const_str_plain_GEN1_I2C_SCL = UNSTREAM_STRING_ASCII( &constant_bin[ 32339 ], 12, 1 );
    const_str_plain_GEN1_I2C_SDA = UNSTREAM_STRING_ASCII( &constant_bin[ 32351 ], 12, 1 );
    const_str_plain_GEN2_I2C_SCL = UNSTREAM_STRING_ASCII( &constant_bin[ 32363 ], 12, 1 );
    const_str_plain_GEN2_I2C_SDA = UNSTREAM_STRING_ASCII( &constant_bin[ 32375 ], 12, 1 );
    const_str_plain_GPIO_EXP_P16 = UNSTREAM_STRING_ASCII( &constant_bin[ 32387 ], 12, 1 );
    const_str_plain_GPIO_EXP_P17 = UNSTREAM_STRING_ASCII( &constant_bin[ 32399 ], 12, 1 );
    const_str_plain_ORANGE_PI_PC = UNSTREAM_STRING_ASCII( &constant_bin[ 32411 ], 12, 1 );
    const_str_plain_ORANGE_PI_R1 = UNSTREAM_STRING_ASCII( &constant_bin[ 32423 ], 12, 1 );
    const_str_plain___builtins__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32435 ], 12, 1 );
    const_str_plain___compiled__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32447 ], 12, 1 );
    const_str_plain___internal__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32459 ], 12, 1 );
    const_str_plain___qualname__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32471 ], 12, 1 );
    const_str_plain_has_location = UNSTREAM_STRING_ASCII( &constant_bin[ 32483 ], 12, 1 );
    const_str_plain_pull_up_down = UNSTREAM_STRING_ASCII( &constant_bin[ 32495 ], 12, 1 );
    const_str_plain_staticmethod = UNSTREAM_STRING_ASCII( &constant_bin[ 32507 ], 12, 1 );
    const_tuple_int_0_none_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_none_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    const_tuple_int_pos_10_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_10_tuple, 0, const_int_pos_10 ); Py_INCREF( const_int_pos_10 );
    const_tuple_int_pos_11_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_11_tuple, 0, const_int_pos_11 ); Py_INCREF( const_int_pos_11 );
    const_tuple_int_pos_12_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_12_tuple, 0, const_int_pos_12 ); Py_INCREF( const_int_pos_12 );
    const_tuple_int_pos_13_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_13_tuple, 0, const_int_pos_13 ); Py_INCREF( const_int_pos_13 );
    const_tuple_int_pos_14_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_14_tuple, 0, const_int_pos_14 ); Py_INCREF( const_int_pos_14 );
    const_tuple_int_pos_15_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_15_tuple, 0, const_int_pos_15 ); Py_INCREF( const_int_pos_15 );
    const_tuple_int_pos_16_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_16_tuple, 0, const_int_pos_16 ); Py_INCREF( const_int_pos_16 );
    const_tuple_int_pos_17_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_17_tuple, 0, const_int_pos_17 ); Py_INCREF( const_int_pos_17 );
    const_tuple_int_pos_18_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_18_tuple, 0, const_int_pos_18 ); Py_INCREF( const_int_pos_18 );
    const_tuple_int_pos_19_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_19_tuple, 0, const_int_pos_19 ); Py_INCREF( const_int_pos_19 );
    const_tuple_int_pos_20_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_20_tuple, 0, const_int_pos_20 ); Py_INCREF( const_int_pos_20 );
    const_tuple_int_pos_21_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_21_tuple, 0, const_int_pos_21 ); Py_INCREF( const_int_pos_21 );
    const_tuple_int_pos_24_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_24_tuple, 0, const_int_pos_24 ); Py_INCREF( const_int_pos_24 );
    const_tuple_int_pos_32_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_32_tuple, 0, const_int_pos_32 ); Py_INCREF( const_int_pos_32 );
    const_tuple_int_pos_64_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_64_tuple, 0, const_int_pos_64 ); Py_INCREF( const_int_pos_64 );
    const_tuple_str_chr_42_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_chr_42_tuple, 0, const_str_chr_42 ); Py_INCREF( const_str_chr_42 );
    const_str_plain_CharlieBonnet = UNSTREAM_STRING_ASCII( &constant_bin[ 16380 ], 13, 1 );
    const_str_plain___metaclass__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32519 ], 13, 1 );
    const_str_plain__initializing = UNSTREAM_STRING_ASCII( &constant_bin[ 32532 ], 13, 1 );
    const_str_plain_circuitpython = UNSTREAM_STRING_ASCII( &constant_bin[ 15578 ], 13, 1 );
    const_str_plain_readfrom_into = UNSTREAM_STRING_ASCII( &constant_bin[ 32545 ], 13, 1 );
    const_tuple_int_0_int_0_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_tuple, 1, const_int_0 ); Py_INCREF( const_int_0 );
    const_tuple_int_pos_116_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_116_tuple, 0, const_int_pos_116 ); Py_INCREF( const_int_pos_116 );
    const_tuple_str_plain_x_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_x_tuple, 0, const_str_plain_x ); Py_INCREF( const_str_plain_x );
    const_tuple_type_object_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type ); Py_INCREF( (PyObject *)&PyBaseObject_Type );
    const_str_plain___orig_bases__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32558 ], 14, 1 );
    const_str_plain_any_beaglebone = UNSTREAM_STRING_ASCII( &constant_bin[ 22324 ], 14, 1 );
    const_str_plain_implementation = UNSTREAM_STRING_ASCII( &constant_bin[ 4671 ], 14, 1 );
    const_str_plain_write_readinto = UNSTREAM_STRING_ASCII( &constant_bin[ 32572 ], 14, 1 );
    const_str_plain___mro_entries__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32586 ], 15, 1 );
    const_str_plain_adafruit_blinka = UNSTREAM_STRING_ASCII( &constant_bin[ 4411 ], 15, 1 );
    const_str_plain_microcontroller = UNSTREAM_STRING_ASCII( &constant_bin[ 4580 ], 15, 1 );
    const_tuple_str_plain_Pin_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Pin_tuple, 0, const_str_plain_Pin ); Py_INCREF( const_str_plain_Pin );
    const_str_plain_DRAGONBOARD_410C = UNSTREAM_STRING_ASCII( &constant_bin[ 32601 ], 16, 1 );
    const_str_plain_any_raspberry_pi = UNSTREAM_STRING_ASCII( &constant_bin[ 21785 ], 16, 1 );
    const_str_plain_get_device_model = UNSTREAM_STRING_ASCII( &constant_bin[ 18564 ], 16, 1 );
    const_tuple_none_none_none_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 0, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_none_none_none_tuple, 2, Py_None ); Py_INCREF( Py_None );
    const_tuple_str_plain_self_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    const_str_plain___class_getitem__ = UNSTREAM_STRING_ASCII( &constant_bin[ 32617 ], 17, 1 );
    const_str_plain_get_cpuinfo_field = UNSTREAM_STRING_ASCII( &constant_bin[ 19543 ], 17, 1 );
    const_tuple_int_0_int_pos_1_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_1_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_1_tuple, 1, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    const_tuple_int_0_int_pos_2_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_2_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_2_tuple, 1, const_int_pos_2 ); Py_INCREF( const_int_pos_2 );
    const_tuple_int_0_int_pos_3_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_3_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_3_tuple, 1, const_int_pos_3 ); Py_INCREF( const_int_pos_3 );
    const_tuple_int_0_int_pos_4_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_4_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_4_tuple, 1, const_int_pos_4 ); Py_INCREF( const_int_pos_4 );
    const_tuple_int_0_int_pos_5_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_5_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_5_tuple, 1, const_int_pos_5 ); Py_INCREF( const_int_pos_5 );
    const_tuple_int_0_int_pos_6_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_6_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_6_tuple, 1, const_int_pos_6 ); Py_INCREF( const_int_pos_6 );
    const_tuple_int_0_int_pos_7_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_7_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_7_tuple, 1, const_int_pos_7 ); Py_INCREF( const_int_pos_7 );
    const_tuple_int_0_int_pos_8_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_8_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_8_tuple, 1, const_int_pos_8 ); Py_INCREF( const_int_pos_8 );
    const_tuple_int_0_int_pos_9_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_9_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_9_tuple, 1, const_int_pos_9 ); Py_INCREF( const_int_pos_9 );
    const_tuple_int_pos_1_int_0_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_int_0_tuple, 0, const_int_pos_1 ); Py_INCREF( const_int_pos_1 );
    PyTuple_SET_ITEM( const_tuple_int_pos_1_int_0_tuple, 1, const_int_0 ); Py_INCREF( const_int_0 );
    const_tuple_int_pos_2_int_0_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_pos_2_int_0_tuple, 0, const_int_pos_2 ); Py_INCREF( const_int_pos_2 );
    PyTuple_SET_ITEM( const_tuple_int_pos_2_int_0_tuple, 1, const_int_0 ); Py_INCREF( const_int_0 );
    const_tuple_str_plain_sleep_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_sleep_tuple, 0, const_str_plain_sleep ); Py_INCREF( const_str_plain_sleep );
    const_str_plain_CORAL_EDGE_TPU_DEV = UNSTREAM_STRING_ASCII( &constant_bin[ 32634 ], 18, 1 );
    const_str_plain_any_embedded_linux = UNSTREAM_STRING_ASCII( &constant_bin[ 22778 ], 18, 1 );
    const_tuple_int_0_int_pos_10_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_10_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_10_tuple, 1, const_int_pos_10 ); Py_INCREF( const_int_pos_10 );
    const_tuple_int_0_int_pos_11_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_11_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_11_tuple, 1, const_int_pos_11 ); Py_INCREF( const_int_pos_11 );
    const_tuple_int_0_int_pos_12_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_12_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_12_tuple, 1, const_int_pos_12 ); Py_INCREF( const_int_pos_12 );
    const_tuple_int_0_int_pos_13_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_13_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_13_tuple, 1, const_int_pos_13 ); Py_INCREF( const_int_pos_13 );
    const_tuple_int_0_int_pos_14_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_14_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_pos_14_tuple, 1, const_int_pos_14 ); Py_INCREF( const_int_pos_14 );
    const_tuple_int_0_none_int_0_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_int_0_none_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_none_int_0_tuple, 1, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_int_0_none_int_0_tuple, 2, const_int_0 ); Py_INCREF( const_int_0 );
    const_str_plain_NotImplementedError = UNSTREAM_STRING_ASCII( &constant_bin[ 32652 ], 19, 1 );
    const_str_plain_adafruit_is31fl3731 = UNSTREAM_STRING_ASCII( &constant_bin[ 15002 ], 19, 1 );
    const_str_plain_read_i2c_block_data = UNSTREAM_STRING_ASCII( &constant_bin[ 3549 ], 19, 1 );
    const_tuple_int_0_int_0_int_0_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_int_0_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_int_0_tuple, 1, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_int_0_int_0_tuple, 2, const_int_0 ); Py_INCREF( const_int_0 );
    const_tuple_str_plain_DAP1_FS_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_DAP1_FS_tuple, 0, const_str_plain_DAP1_FS ); Py_INCREF( const_str_plain_DAP1_FS );
    const_tuple_str_plain_AUD_MCLK_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_AUD_MCLK_tuple, 0, const_str_plain_AUD_MCLK ); Py_INCREF( const_str_plain_AUD_MCLK );
    const_tuple_str_plain_DAP1_DIN_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_DAP1_DIN_tuple, 0, const_str_plain_DAP1_DIN ); Py_INCREF( const_str_plain_DAP1_DIN );
    const_tuple_str_plain_SPI1_CS0_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_SPI1_CS0_tuple, 0, const_str_plain_SPI1_CS0 ); Py_INCREF( const_str_plain_SPI1_CS0 );
    const_tuple_str_plain_SPI1_CS1_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_SPI1_CS1_tuple, 0, const_str_plain_SPI1_CS1 ); Py_INCREF( const_str_plain_SPI1_CS1 );
    const_tuple_str_plain_SPI1_SCK_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_SPI1_SCK_tuple, 0, const_str_plain_SPI1_SCK ); Py_INCREF( const_str_plain_SPI1_SCK );
    const_str_plain_get_device_compatible = UNSTREAM_STRING_ASCII( &constant_bin[ 18589 ], 21, 1 );
    const_str_plain_writeto_then_readfrom = UNSTREAM_STRING_ASCII( &constant_bin[ 9735 ], 21, 1 );
    const_tuple_str_plain_DAP1_DOUT_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_DAP1_DOUT_tuple, 0, const_str_plain_DAP1_DOUT ); Py_INCREF( const_str_plain_DAP1_DOUT );
    const_tuple_str_plain_DAP1_SCLK_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_DAP1_SCLK_tuple, 0, const_str_plain_DAP1_SCLK ); Py_INCREF( const_str_plain_DAP1_SCLK );
    const_tuple_str_plain_SPI1_MISO_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_SPI1_MISO_tuple, 0, const_str_plain_SPI1_MISO ); Py_INCREF( const_str_plain_SPI1_MISO );
    const_tuple_str_plain_SPI1_MOSI_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_SPI1_MOSI_tuple, 0, const_str_plain_SPI1_MOSI ); Py_INCREF( const_str_plain_SPI1_MOSI );
    const_tuple_str_plain_UART1_CTS_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_UART1_CTS_tuple, 0, const_str_plain_UART1_CTS ); Py_INCREF( const_str_plain_UART1_CTS );
    const_tuple_str_plain_UART1_RTS_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_UART1_RTS_tuple, 0, const_str_plain_UART1_RTS ); Py_INCREF( const_str_plain_UART1_RTS );
    const_tuple_str_plain___class___tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain___class___tuple, 0, const_str_plain___class__ ); Py_INCREF( const_str_plain___class__ );
    const_str_plain_adafruit_platformdetect = UNSTREAM_STRING_ASCII( &constant_bin[ 19001 ], 23, 1 );
    const_str_plain_any_raspberry_pi_40_pin = UNSTREAM_STRING_ASCII( &constant_bin[ 21785 ], 23, 1 );
    const_tuple_int_0_none_int_0_none_tuple = PyTuple_New( 4 );
    PyTuple_SET_ITEM( const_tuple_int_0_none_int_0_none_tuple, 0, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_none_int_0_none_tuple, 1, Py_None ); Py_INCREF( Py_None );
    PyTuple_SET_ITEM( const_tuple_int_0_none_int_0_none_tuple, 2, const_int_0 ); Py_INCREF( const_int_0 );
    PyTuple_SET_ITEM( const_tuple_int_0_none_int_0_none_tuple, 3, Py_None ); Py_INCREF( Py_None );
    const_tuple_str_plain_GEN1_I2C_SCL_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_GEN1_I2C_SCL_tuple, 0, const_str_plain_GEN1_I2C_SCL ); Py_INCREF( const_str_plain_GEN1_I2C_SCL );
    const_tuple_str_plain_GEN1_I2C_SDA_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_GEN1_I2C_SDA_tuple, 0, const_str_plain_GEN1_I2C_SDA ); Py_INCREF( const_str_plain_GEN1_I2C_SDA );
    const_tuple_str_plain_GEN2_I2C_SCL_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_GEN2_I2C_SCL_tuple, 0, const_str_plain_GEN2_I2C_SCL ); Py_INCREF( const_str_plain_GEN2_I2C_SCL );
    const_tuple_str_plain_GEN2_I2C_SDA_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_GEN2_I2C_SDA_tuple, 0, const_str_plain_GEN2_I2C_SDA ); Py_INCREF( const_str_plain_GEN2_I2C_SDA );
    const_tuple_str_plain_GPIO_EXP_P16_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_GPIO_EXP_P16_tuple, 0, const_str_plain_GPIO_EXP_P16 ); Py_INCREF( const_str_plain_GPIO_EXP_P16 );
    const_tuple_str_plain_GPIO_EXP_P17_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_plain_GPIO_EXP_P17_tuple, 0, const_str_plain_GPIO_EXP_P17 ); Py_INCREF( const_str_plain_GPIO_EXP_P17 );
    const_str_plain_check_dt_compatible_value = UNSTREAM_STRING_ASCII( &constant_bin[ 18495 ], 25, 1 );
    const_str_plain_get_armbian_release_field = UNSTREAM_STRING_ASCII( &constant_bin[ 18914 ], 25, 1 );
    const_tuple_tuple_int_0_int_0_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_0_tuple_tuple, 0, const_tuple_int_0_int_0_tuple ); Py_INCREF( const_tuple_int_0_int_0_tuple );
    const_str_plain_submodule_search_locations = UNSTREAM_STRING_ASCII( &constant_bin[ 32671 ], 26, 1 );
    const_dict_8aeb909f6fefcf5760c5c4604f52a0cc = _PyDict_NewPresized( 3 );
    PyDict_SetItem( const_dict_8aeb909f6fefcf5760c5c4604f52a0cc, const_str_plain_start, const_int_0 );
    PyDict_SetItem( const_dict_8aeb909f6fefcf5760c5c4604f52a0cc, const_str_plain_end, Py_None );
    PyDict_SetItem( const_dict_8aeb909f6fefcf5760c5c4604f52a0cc, const_str_plain_stop, Py_True );
    assert( PyDict_Size( const_dict_8aeb909f6fefcf5760c5c4604f52a0cc ) == 3 );
    const_dict_bd9acfb6650818d787e11cf74e7981d1 = _PyDict_NewPresized( 5 );
    PyDict_SetItem( const_dict_bd9acfb6650818d787e11cf74e7981d1, const_str_plain_out_start, const_int_0 );
    PyDict_SetItem( const_dict_bd9acfb6650818d787e11cf74e7981d1, const_str_plain_out_end, Py_None );
    PyDict_SetItem( const_dict_bd9acfb6650818d787e11cf74e7981d1, const_str_plain_in_start, const_int_0 );
    PyDict_SetItem( const_dict_bd9acfb6650818d787e11cf74e7981d1, const_str_plain_in_end, Py_None );
    PyDict_SetItem( const_dict_bd9acfb6650818d787e11cf74e7981d1, const_str_plain_stop, Py_False );
    assert( PyDict_Size( const_dict_bd9acfb6650818d787e11cf74e7981d1 ) == 5 );
    const_tuple_str_plain_Pin_tuple_empty_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_Pin_tuple_empty_tuple, 0, const_str_plain_Pin ); Py_INCREF( const_str_plain_Pin );
    PyTuple_SET_ITEM( const_tuple_str_plain_Pin_tuple_empty_tuple, 1, const_tuple_empty ); Py_INCREF( const_tuple_empty );
    const_tuple_tuple_int_0_int_pos_1_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_1_tuple_tuple, 0, const_tuple_int_0_int_pos_1_tuple ); Py_INCREF( const_tuple_int_0_int_pos_1_tuple );
    const_tuple_tuple_int_0_int_pos_2_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_2_tuple_tuple, 0, const_tuple_int_0_int_pos_2_tuple ); Py_INCREF( const_tuple_int_0_int_pos_2_tuple );
    const_tuple_tuple_int_0_int_pos_3_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_3_tuple_tuple, 0, const_tuple_int_0_int_pos_3_tuple ); Py_INCREF( const_tuple_int_0_int_pos_3_tuple );
    const_tuple_tuple_int_0_int_pos_4_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_4_tuple_tuple, 0, const_tuple_int_0_int_pos_4_tuple ); Py_INCREF( const_tuple_int_0_int_pos_4_tuple );
    const_tuple_tuple_int_0_int_pos_5_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_5_tuple_tuple, 0, const_tuple_int_0_int_pos_5_tuple ); Py_INCREF( const_tuple_int_0_int_pos_5_tuple );
    const_tuple_tuple_int_0_int_pos_6_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_6_tuple_tuple, 0, const_tuple_int_0_int_pos_6_tuple ); Py_INCREF( const_tuple_int_0_int_pos_6_tuple );
    const_tuple_tuple_int_0_int_pos_7_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_7_tuple_tuple, 0, const_tuple_int_0_int_pos_7_tuple ); Py_INCREF( const_tuple_int_0_int_pos_7_tuple );
    const_tuple_tuple_int_0_int_pos_8_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_8_tuple_tuple, 0, const_tuple_int_0_int_pos_8_tuple ); Py_INCREF( const_tuple_int_0_int_pos_8_tuple );
    const_tuple_tuple_int_0_int_pos_9_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_9_tuple_tuple, 0, const_tuple_int_0_int_pos_9_tuple ); Py_INCREF( const_tuple_int_0_int_pos_9_tuple );
    const_str_plain_NUITKA_PACKAGE_adafruit_blinka = UNSTREAM_STRING_ASCII( &constant_bin[ 5748 ], 30, 1 );
    const_tuple_str_plain_self_str_plain_val_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_val_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_val_tuple, 1, const_str_plain_val ); Py_INCREF( const_str_plain_val );
    const_tuple_tuple_int_0_int_pos_10_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_10_tuple_tuple, 0, const_tuple_int_0_int_pos_10_tuple ); Py_INCREF( const_tuple_int_0_int_pos_10_tuple );
    const_tuple_tuple_int_0_int_pos_11_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_11_tuple_tuple, 0, const_tuple_int_0_int_pos_11_tuple ); Py_INCREF( const_tuple_int_0_int_pos_11_tuple );
    const_tuple_tuple_int_0_int_pos_12_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_12_tuple_tuple, 0, const_tuple_int_0_int_pos_12_tuple ); Py_INCREF( const_tuple_int_0_int_pos_12_tuple );
    const_tuple_tuple_int_0_int_pos_13_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_13_tuple_tuple, 0, const_tuple_int_0_int_pos_13_tuple ); Py_INCREF( const_tuple_int_0_int_pos_13_tuple );
    const_tuple_tuple_int_0_int_pos_14_tuple_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_tuple_int_0_int_pos_14_tuple_tuple, 0, const_tuple_int_0_int_pos_14_tuple ); Py_INCREF( const_tuple_int_0_int_pos_14_tuple );
    const_tuple_str_plain_self_str_plain_attr_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_attr_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_attr_tuple, 1, const_str_plain_attr ); Py_INCREF( const_str_plain_attr );
    const_bytearray_7734633b10e3c30456916281c56d3a40 = UNSTREAM_BYTEARRAY( &constant_bin[ 721 ], 1 );
    const_tuple_str_plain_self_str_plain_other_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_other_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_other_tuple, 1, const_str_plain_other ); Py_INCREF( const_str_plain_other );
    const_tuple_str_plain_self_str_plain_value_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_value_tuple, 1, const_str_plain_value ); Py_INCREF( const_str_plain_value );
    const_str_digest_0121c319bd84ff9d6a5138e9bbbd3657 = UNSTREAM_STRING_ASCII( &constant_bin[ 32697 ], 21, 0 );
    const_str_digest_042902472e0ae572ba4bf463d0fc37cd = UNSTREAM_STRING_ASCII( &constant_bin[ 32718 ], 18, 0 );
    const_str_digest_050b893f9859457a2cb9a6e5acd06e19 = UNSTREAM_STRING_ASCII( &constant_bin[ 14002 ], 42, 0 );
    const_str_digest_0c1898fc1f2c6d20fef19765d7f4025d = UNSTREAM_STRING_ASCII( &constant_bin[ 12052 ], 54, 0 );
    const_str_digest_0daddf6c4886f3926c22848feb4b084b = UNSTREAM_STRING_ASCII( &constant_bin[ 32736 ], 17, 0 );
    const_str_digest_0e0545f125585b80111045982f829c0c = UNSTREAM_STRING_ASCII( &constant_bin[ 9980 ], 49, 0 );
    const_str_digest_107b02ad77d67bbaaf288881f3e4530b = UNSTREAM_STRING_ASCII( &constant_bin[ 13417 ], 52, 1 );
    const_str_digest_169d01c053c9b40bcaa545433f06946e = UNSTREAM_STRING_ASCII( &constant_bin[ 32753 ], 24, 0 );
    const_str_digest_16a1f1b35028934e483cb53805cc0f5e = UNSTREAM_STRING_ASCII( &constant_bin[ 8034 ], 54, 1 );
    const_str_digest_1d1f43dfbb93e60d00ee0e787d075dd3 = UNSTREAM_STRING_ASCII( &constant_bin[ 9427 ], 43, 0 );
    const_str_digest_204795fc719a5f4d79004b19ebaaa4f0 = UNSTREAM_STRING_ASCII( &constant_bin[ 32777 ], 12, 0 );
    const_str_digest_2134f552f340f7ce0a8a355bdaa826fe = UNSTREAM_STRING_ASCII( &constant_bin[ 23509 ], 28, 0 );
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING_ASCII( &constant_bin[ 30858 ], 2, 0 );
    const_str_digest_27590e9627cdd4999c774bf4c1f1962f = UNSTREAM_STRING_ASCII( &constant_bin[ 9041 ], 43, 0 );
    const_str_digest_2924342b5bc89f7a19a02b6ab2742f1e = UNSTREAM_STRING_ASCII( &constant_bin[ 13663 ], 46, 0 );
    const_str_digest_2ab60b4f55405026964a3306bc31e42a = UNSTREAM_STRING_ASCII( &constant_bin[ 32789 ], 25, 0 );
    const_str_digest_2c2105051be275e3a013884311f3861a = UNSTREAM_STRING_ASCII( &constant_bin[ 9206 ], 39, 0 );
    const_str_digest_35a61f90709e302b9e7a525c10ab66a6 = UNSTREAM_STRING_ASCII( &constant_bin[ 6357 ], 46, 1 );
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING_ASCII( &constant_bin[ 4515 ], 7, 0 );
    const_str_digest_461f5cb03aca48d6eb285a5f7999fc4a = UNSTREAM_STRING_ASCII( &constant_bin[ 5305 ], 24, 0 );
    const_str_digest_4dc5c42f81dddc562102970a99074af7 = UNSTREAM_STRING_ASCII( &constant_bin[ 32814 ], 24, 0 );
    const_str_digest_4e256d114264995ca73901ec126f97c3 = UNSTREAM_STRING_ASCII( &constant_bin[ 32838 ], 8, 0 );
    const_str_digest_4e7aad7c88b0724a830e614462e04cb4 = UNSTREAM_STRING_ASCII( &constant_bin[ 31088 ], 19, 0 );
    const_str_digest_4ebeeb801387999c9452758cfcfb1249 = UNSTREAM_STRING_ASCII( &constant_bin[ 13131 ], 41, 0 );
    const_str_digest_4fbae985f092f4091e6fdcac3426d015 = UNSTREAM_STRING_ASCII( &constant_bin[ 32846 ], 12, 0 );
    const_str_digest_53178c0da82ef51e90b9f05eeb3d3a08 = UNSTREAM_STRING_ASCII( &constant_bin[ 32858 ], 28, 0 );
    const_str_digest_53237157d5303abb9ce2918790913279 = UNSTREAM_STRING_ASCII( &constant_bin[ 13066 ], 37, 0 );
    const_str_digest_58961c73026e70b23b08cf381b49e04e = UNSTREAM_STRING_ASCII( &constant_bin[ 32886 ], 15, 0 );
    const_str_digest_5b09d1d161877c85e90f4776974a2533 = UNSTREAM_STRING_ASCII( &constant_bin[ 32901 ], 11, 0 );
    const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 = UNSTREAM_STRING_ASCII( &constant_bin[ 32912 ], 9, 0 );
    const_str_digest_61d3bd56be0becb53ea5a64883eefdcd = UNSTREAM_STRING_ASCII( &constant_bin[ 6424 ], 44, 0 );
    const_str_digest_64a851b331b809947b90aaf0f1eaaede = UNSTREAM_STRING_ASCII( &constant_bin[ 11034 ], 41, 0 );
    const_str_digest_6ef1c1de74d4522c07e3c7ee482b7a61 = UNSTREAM_STRING_ASCII( &constant_bin[ 13572 ], 42, 0 );
    const_str_digest_6fba6dcdb09ebe74c73d220c28a4c8b9 = UNSTREAM_STRING_ASCII( &constant_bin[ 32921 ], 12, 0 );
    const_str_digest_75fd71b1edada749c2ef7ac810062295 = UNSTREAM_STRING_ASCII( &constant_bin[ 32933 ], 46, 0 );
    const_str_digest_7b1b39b143d57c01cb563cf6e2abebeb = UNSTREAM_STRING_ASCII( &constant_bin[ 6487 ], 48, 0 );
    const_str_digest_80a4805bdbd3485ea876d5c515fef787 = UNSTREAM_STRING_ASCII( &constant_bin[ 32979 ], 34, 0 );
    const_str_digest_840781f3bcbba24c0c9d94a22c7c54d4 = UNSTREAM_STRING_ASCII( &constant_bin[ 8539 ], 48, 0 );
    const_str_digest_8a90b7bc90ab321ed5fdeb2f8c407d36 = UNSTREAM_STRING_ASCII( &constant_bin[ 32718 ], 9, 0 );
    const_str_digest_8eeb75553705ba0dd652b93d50f3a4ac = UNSTREAM_STRING_ASCII( &constant_bin[ 10757 ], 49, 0 );
    const_str_digest_96e349fb739b35937b0a66e566327387 = UNSTREAM_STRING_ASCII( &constant_bin[ 33013 ], 10, 0 );
    const_str_digest_a92f659b27c80c84236371e5d850c570 = UNSTREAM_STRING_ASCII( &constant_bin[ 22435 ], 29, 0 );
    const_str_digest_adb728c6c2e334e1f32698032cda0934 = UNSTREAM_STRING_ASCII( &constant_bin[ 33023 ], 8, 0 );
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING_ASCII( &constant_bin[ 33031 ], 47, 0 );
    const_str_digest_aeadebb446eb9697b49f22d96463f59a = UNSTREAM_STRING_ASCII( &constant_bin[ 10543 ], 58, 0 );
    const_str_digest_b26fd46e1b0aded1fdd3dde6bf5999b8 = UNSTREAM_STRING_ASCII( &constant_bin[ 33078 ], 34, 0 );
    const_str_digest_b6c4491781143616325da56a91971a7c = UNSTREAM_STRING_ASCII( &constant_bin[ 6708 ], 38, 0 );
    const_str_digest_b7d128ea5b23af8ee5685b8834d9b56c = UNSTREAM_STRING_ASCII( &constant_bin[ 14497 ], 42, 0 );
    const_str_digest_c48e26755342fb3a8811b1a101a4718e = UNSTREAM_STRING_ASCII( &constant_bin[ 33112 ], 11, 0 );
    const_str_digest_c606d455df1b0b1ff46033ccb0d515a0 = UNSTREAM_STRING_ASCII( &constant_bin[ 7761 ], 42, 0 );
    const_str_digest_cd071a97bd54c729d1fabb270c277385 = UNSTREAM_STRING_ASCII( &constant_bin[ 25606 ], 14, 0 );
    const_str_digest_cea0edda4a37f9b21d5f316ef41250c8 = UNSTREAM_STRING_ASCII( &constant_bin[ 11514 ], 41, 0 );
    const_str_digest_d0fff785ff78971c897b548f07ba60ad = UNSTREAM_STRING_ASCII( &constant_bin[ 11269 ], 45, 0 );
    const_str_digest_d1aaf6d901a3f894393de994d52a5367 = UNSTREAM_STRING_ASCII( &constant_bin[ 14218 ], 46, 0 );
    const_str_digest_d5751cb219abc30399a2d639a5973dea = UNSTREAM_STRING_ASCII( &constant_bin[ 33123 ], 12, 0 );
    const_str_digest_efdbb1146d6752472c0f8c671fd9deb5 = UNSTREAM_STRING_ASCII( &constant_bin[ 14878 ], 46, 0 );
    const_str_digest_f158e8772f2a5f3a55bc0908728823bc = UNSTREAM_STRING_ASCII( &constant_bin[ 33135 ], 46, 0 );
    const_str_digest_f25895fd22019cc3589993928699e319 = UNSTREAM_STRING_ASCII( &constant_bin[ 33181 ], 12, 0 );
    const_str_digest_f46d0ef2d0a087f27969836562e28680 = UNSTREAM_STRING_ASCII( &constant_bin[ 33193 ], 9, 0 );
    const_str_digest_f4a5b997d0b3c1411d2a276dc0aa3d6e = UNSTREAM_STRING_ASCII( &constant_bin[ 32789 ], 11, 0 );
    const_str_digest_f570069e0d46f80dd06443468800a290 = UNSTREAM_STRING_ASCII( &constant_bin[ 32886 ], 4, 0 );
    const_str_digest_f593149bdea4cd8b2f0da587c0d8b83e = UNSTREAM_STRING_ASCII( &constant_bin[ 11837 ], 57, 1 );
    const_str_digest_fb6ee4778f1d62cd8875c5cfe7b93017 = UNSTREAM_STRING_ASCII( &constant_bin[ 8894 ], 39, 0 );
    const_str_digest_fd4e498744c79a83acf09eec95362b39 = UNSTREAM_STRING_ASCII( &constant_bin[ 11440 ], 37, 0 );
    const_str_digest_ff1a1456313d3e886477e5ceffe8c72d = UNSTREAM_STRING_ASCII( &constant_bin[ 2554 ], 21, 0 );
    const_tuple_str_plain_self_str_plain_pin_id_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_pin_id_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_pin_id_tuple, 1, const_str_plain_pin_id ); Py_INCREF( const_str_plain_pin_id );
    const_tuple_4056a0ef07ec9188d15ce9b607833855_tuple = PyTuple_New( 4 );
    PyTuple_SET_ITEM( const_tuple_4056a0ef07ec9188d15ce9b607833855_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_4056a0ef07ec9188d15ce9b607833855_tuple, 1, const_str_plain_exc_type ); Py_INCREF( const_str_plain_exc_type );
    PyTuple_SET_ITEM( const_tuple_4056a0ef07ec9188d15ce9b607833855_tuple, 2, const_str_plain_exc_value ); Py_INCREF( const_str_plain_exc_value );
    PyTuple_SET_ITEM( const_tuple_4056a0ef07ec9188d15ce9b607833855_tuple, 3, const_str_plain_traceback ); Py_INCREF( const_str_plain_traceback );
    const_tuple_495dd9d89d9634ae663598256e6465a5_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_495dd9d89d9634ae663598256e6465a5_tuple, 0, const_str_plain_NUITKA_PACKAGE_adafruit_blinka ); Py_INCREF( const_str_plain_NUITKA_PACKAGE_adafruit_blinka );
    PyTuple_SET_ITEM( const_tuple_495dd9d89d9634ae663598256e6465a5_tuple, 1, const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 ); Py_INCREF( const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 );
    const_tuple_6f70ce55669238251e7d6cf7fde5f256_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_6f70ce55669238251e7d6cf7fde5f256_tuple, 0, const_str_digest_107b02ad77d67bbaaf288881f3e4530b ); Py_INCREF( const_str_digest_107b02ad77d67bbaaf288881f3e4530b );
    PyTuple_SET_ITEM( const_tuple_6f70ce55669238251e7d6cf7fde5f256_tuple, 1, const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 ); Py_INCREF( const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 );
    const_tuple_8b75eea508b9ef665b6900efe85bbade_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_8b75eea508b9ef665b6900efe85bbade_tuple, 0, const_str_digest_35a61f90709e302b9e7a525c10ab66a6 ); Py_INCREF( const_str_digest_35a61f90709e302b9e7a525c10ab66a6 );
    PyTuple_SET_ITEM( const_tuple_8b75eea508b9ef665b6900efe85bbade_tuple, 1, const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 ); Py_INCREF( const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 );
    const_tuple_c5266559b4545301f11ca05d84cab86b_tuple = PyTuple_New( 6 );
    PyTuple_SET_ITEM( const_tuple_c5266559b4545301f11ca05d84cab86b_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_c5266559b4545301f11ca05d84cab86b_tuple, 1, const_str_plain_address ); Py_INCREF( const_str_plain_address );
    PyTuple_SET_ITEM( const_tuple_c5266559b4545301f11ca05d84cab86b_tuple, 2, const_str_plain_buffer ); Py_INCREF( const_str_plain_buffer );
    PyTuple_SET_ITEM( const_tuple_c5266559b4545301f11ca05d84cab86b_tuple, 3, const_str_plain_start ); Py_INCREF( const_str_plain_start );
    PyTuple_SET_ITEM( const_tuple_c5266559b4545301f11ca05d84cab86b_tuple, 4, const_str_plain_end ); Py_INCREF( const_str_plain_end );
    PyTuple_SET_ITEM( const_tuple_c5266559b4545301f11ca05d84cab86b_tuple, 5, const_str_plain_stop ); Py_INCREF( const_str_plain_stop );
    const_tuple_e6f453f188d84e241b37d93bda687549_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_e6f453f188d84e241b37d93bda687549_tuple, 0, const_str_digest_f593149bdea4cd8b2f0da587c0d8b83e ); Py_INCREF( const_str_digest_f593149bdea4cd8b2f0da587c0d8b83e );
    PyTuple_SET_ITEM( const_tuple_e6f453f188d84e241b37d93bda687549_tuple, 1, const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 ); Py_INCREF( const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 );
    const_tuple_fc0ac972cbd41df5dfec11db5338b333_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_fc0ac972cbd41df5dfec11db5338b333_tuple, 0, const_str_digest_16a1f1b35028934e483cb53805cc0f5e ); Py_INCREF( const_str_digest_16a1f1b35028934e483cb53805cc0f5e );
    PyTuple_SET_ITEM( const_tuple_fc0ac972cbd41df5dfec11db5338b333_tuple, 1, const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 ); Py_INCREF( const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 );
    const_tuple_str_plain_self_str_plain_detector_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_detector_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_detector_tuple, 1, const_str_plain_detector ); Py_INCREF( const_str_plain_detector );
    const_tuple_str_plain_self_str_plain_bcm_number_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_bcm_number_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_bcm_number_tuple, 1, const_str_plain_bcm_number ); Py_INCREF( const_str_plain_bcm_number );
    const_tuple_str_digest_53178c0da82ef51e90b9f05eeb3d3a08_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_53178c0da82ef51e90b9f05eeb3d3a08_tuple, 0, const_str_digest_53178c0da82ef51e90b9f05eeb3d3a08 ); Py_INCREF( const_str_digest_53178c0da82ef51e90b9f05eeb3d3a08 );
    const_tuple_str_digest_b26fd46e1b0aded1fdd3dde6bf5999b8_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_b26fd46e1b0aded1fdd3dde6bf5999b8_tuple, 0, const_str_digest_b26fd46e1b0aded1fdd3dde6bf5999b8 ); Py_INCREF( const_str_digest_b26fd46e1b0aded1fdd3dde6bf5999b8 );
    const_tuple_str_digest_f158e8772f2a5f3a55bc0908728823bc_tuple = PyTuple_New( 1 );
    PyTuple_SET_ITEM( const_tuple_str_digest_f158e8772f2a5f3a55bc0908728823bc_tuple, 0, const_str_digest_f158e8772f2a5f3a55bc0908728823bc ); Py_INCREF( const_str_digest_f158e8772f2a5f3a55bc0908728823bc );
    const_tuple_str_plain_self_str_plain_mode_str_plain_pull_tuple = PyTuple_New( 3 );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_mode_str_plain_pull_tuple, 0, const_str_plain_self ); Py_INCREF( const_str_plain_self );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_mode_str_plain_pull_tuple, 1, const_str_plain_mode ); Py_INCREF( const_str_plain_mode );
    PyTuple_SET_ITEM( const_tuple_str_plain_self_str_plain_mode_str_plain_pull_tuple, 2, const_str_plain_pull ); Py_INCREF( const_str_plain_pull );
    const_tuple_anon_function_anon_builtin_function_or_method_tuple = PyTuple_New( 2 );
    PyTuple_SET_ITEM( const_tuple_anon_function_anon_builtin_function_or_method_tuple, 0, (PyObject *)&PyFunction_Type ); Py_INCREF( (PyObject *)&PyFunction_Type );
    PyTuple_SET_ITEM( const_tuple_anon_function_anon_builtin_function_or_method_tuple, 1, (PyObject *)&PyCFunction_Type ); Py_INCREF( (PyObject *)&PyCFunction_Type );

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_58961c73026e70b23b08cf381b49e04e
    );

#ifndef _NUITKA_STANDALONE
    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"exec_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );


#if PYTHON_VERSION >= 300
    /* Set the "sys.base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

    /* Set the "sys.exec_base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_exec_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

#endif
#endif
#endif

    static PyTypeObject Nuitka_VersionInfoType;

    // Same fields as "sys.version_info" except no serial number.
    static PyStructSequence_Field Nuitka_VersionInfoFields[] = {
        {(char *)"major", (char *)"Major release number"},
        {(char *)"minor", (char *)"Minor release number"},
        {(char *)"micro", (char *)"Micro release number"},
        {(char *)"releaselevel", (char *)"'alpha', 'beta', 'candidate', or 'release'"},
        {0}
    };

    static PyStructSequence_Desc Nuitka_VersionInfoDesc = {
        (char *)"__nuitka_version__",                                    /* name */
        (char *)"__compiled__\n\nVersion information as a named tuple.", /* doc */
        Nuitka_VersionInfoFields,                                        /* fields */
        4
    };

    PyStructSequence_InitType(&Nuitka_VersionInfoType, &Nuitka_VersionInfoDesc);

    Nuitka_dunder_compiled_value = PyStructSequence_New(&Nuitka_VersionInfoType);
    assert(Nuitka_dunder_compiled_value != NULL);

    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 0, PyInt_FromLong(0));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 1, PyInt_FromLong(6));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 2, PyInt_FromLong(4));

#if PYTHON_VERSION < 300
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, PyString_FromString("release"));
#else
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, PyUnicode_FromString("release"));
#endif
    // Prevent users from creating the Nuitka version type object.
    Nuitka_VersionInfoType.tp_init = NULL;
    Nuitka_VersionInfoType.tp_new = NULL;


}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants( void )
{

}
#endif

void createGlobalConstants( void )
{
    if ( _sentinel_value == NULL )
    {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr( NULL, NULL );
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New( (void *)27, "sentinel", NULL );
#endif
        assert( _sentinel_value );

        _createGlobalConstants();
    }
}
